openapi: 3.2.0
info:
  version: storefront-v1
  title: Storefront API V1 Googlepay API
servers:
- url: https://dogfood.commerce.insitesandbox.com
security: []
tags:
- name: Googlepay
paths:
  /api/v1/googlepay/config:
    get:
      tags:
      - Googlepay
      operationId: GooglePayV1_Get
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
            text/json:
              schema:
                type: object
            application/xml:
              schema:
                type: object
            text/xml:
              schema:
                type: object
            text/html:
              schema:
                type: object
      security:
      - access_token: []
components:
  securitySchemes:
    access_token:
      type: apiKey
      description: Token used to access storefront API.
      name: access_token
      in: query
