openapi: 3.2.0
info:
  version: admin-v1
  title: Admin API V1 Content Page States API
servers:
- url: https://dogfood.commerce.insitesandbox.com
security: []
tags:
- name: Content Page States
paths:
  /api/v1/admin/ContentPageStates:
    get:
      tags:
      - Content Page States
      summary: Returns the EntitySet ContentPageStates
      operationId: ContentPageStates_Get
      parameters:
      - name: $expand
        in: query
        description: Expands related entities inline.
        required: false
        schema:
          type: string
      - name: $filter
        in: query
        description: Filters the results, based on a Boolean condition.
        required: false
        schema:
          type: string
      - name: $select
        in: query
        description: Selects which properties to include in the response.
        required: false
        schema:
          type: string
      - name: $apply
        in: query
        description: Aggregates the results according to one or more transformations.
        required: false
        schema:
          type: string
      - name: $orderby
        in: query
        description: Sorts the results.
        required: false
        schema:
          type: string
      - name: $top
        in: query
        description: Returns only the first n results.
        required: false
        schema:
          type: integer
          format: int32
      - name: $skip
        in: query
        description: Skips the first n results.
        required: false
        schema:
          type: integer
          format: int32
      - name: $count
        in: query
        description: Includes a count of the matching results in the response.
        required: false
        schema:
          type: boolean
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                type: object
      deprecated: false
      security:
      - access_token: []
    post:
      tags:
      - Content Page States
      summary: Post a new entity to EntitySet ContentPageStates
      operationId: ContentPageStates_Post
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Insite.Data.Entities.ContentPageState'
        description: The entity to post
        required: true
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                type: object
      deprecated: false
      security:
      - access_token: []
  /api/v1/admin/ContentPageStates({id}):
    get:
      tags:
      - Content Page States
      summary: Returns the entity with the key from ContentPageStates
      operationId: ContentPageStates_GetById
      parameters:
      - name: id
        in: path
        description: 'key: id'
        required: true
        schema:
          type: string
          format: uuid
      - name: $expand
        in: query
        description: Expands related entities inline.
        required: false
        schema:
          type: string
      - name: $select
        in: query
        description: Selects which properties to include in the response.
        required: false
        schema:
          type: string
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                type: object
      deprecated: false
      security:
      - access_token: []
    put:
      tags:
      - Content Page States
      summary: Replace entity in EntitySet ContentPageStates
      operationId: ContentPageStates_PutById
      parameters:
      - name: id
        in: path
        description: 'key: id'
        required: true
        schema:
          type: string
          format: uuid
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Insite.Data.Entities.ContentPageState'
        description: The entity to put
        required: true
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                type: object
      deprecated: false
      security:
      - access_token: []
    delete:
      tags:
      - Content Page States
      summary: Delete entity in EntitySet ContentPageStates
      operationId: ContentPageStates_DeleteById
      parameters:
      - name: id
        in: path
        description: 'key: id'
        required: true
        schema:
          type: string
          format: uuid
      - name: If-Match
        in: header
        description: If-Match header
        required: false
        schema:
          type: string
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                type: object
      deprecated: false
      security:
      - access_token: []
    patch:
      tags:
      - Content Page States
      summary: Update entity in EntitySet ContentPageStates
      operationId: ContentPageStates_PatchById
      parameters:
      - name: id
        in: path
        description: 'key: id'
        required: true
        schema:
          type: string
          format: uuid
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Insite.Data.Entities.ContentPageState'
        description: The entity to patch
        required: true
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                type: object
      deprecated: false
      security:
      - access_token: []
  /api/v1/admin/ContentPageStates/Default.Default():
    get:
      tags:
      - Content Page States
      summary: Call operation  Default
      operationId: ContentPageStates_Default
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                type: object
      deprecated: false
      security:
      - access_token: []
  /api/v1/admin/contentpagestates/delete:
    delete:
      tags:
      - Content Page States
      operationId: ContentPageStates_DeleteRoute
      parameters:
      - name: ids
        in: query
        required: true
        explode: true
        schema:
          type: array
          items:
            type: string
            format: uuid
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                type: object
      deprecated: false
      security:
      - access_token: []
  /api/v1/admin/contentpagestates({key})/customproperties({custompropertyKey}):
    get:
      tags:
      - Content Page States
      operationId: ContentPageStates_GetCustomPropertyByKeyAndCustompropertykey
      parameters:
      - name: key
        in: path
        required: true
        schema:
          type: string
          format: uuid
      - name: custompropertyKey
        in: path
        required: true
        schema:
          type: string
          format: uuid
      - name: $expand
        in: query
        description: Expands related entities inline.
        required: false
        schema:
          type: string
      - name: $select
        in: query
        description: Selects which properties to include in the response.
        required: false
        schema:
          type: string
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                type: object
      deprecated: false
      security:
      - access_token: []
components:
  schemas:
    Insite.Data.Entities.ContentPageState:
      required:
      - name
      - variantName
      - path
      type: object
      properties:
        id:
          format: uuid
          type: string
          example: 00000000-0000-0000-0000-000000000000
        websiteId:
          format: uuid
          type: string
          example: 00000000-0000-0000-0000-000000000000
        contentKey:
          format: int32
          type: integer
        variantKey:
          format: int32
          type: integer
        linkedToContentKey:
          format: int32
          type: integer
        name:
          maxLength: 50
          minLength: 0
          type: string
        variantName:
          maxLength: 50
          minLength: 0
          type: string
        path:
          maxLength: 500
          minLength: 0
          type: string
        sortOrder:
          format: int32
          type: integer
        languageId:
          format: uuid
          type: string
          example: 00000000-0000-0000-0000-000000000000
        personaId:
          format: uuid
          type: string
          example: 00000000-0000-0000-0000-000000000000
        deviceType:
          maxLength: 50
          minLength: 0
          type: string
        publishOn:
          format: date-time
          type: string
        futurePublishOn:
          format: date-time
          type: string
        isUnpublished:
          type: boolean
        isWaitingForApproval:
          type: boolean
        isRetracted:
          type: boolean
        isDeletable:
          type: boolean
        isVariant:
          type: boolean
        isDefaultVariant:
          type: boolean
        experimentId:
          format: uuid
          type: string
          example: 00000000-0000-0000-0000-000000000000
        isExperiment:
          type: boolean
        isExperimentVariant:
          type: boolean
        experimentStatus:
          type: string
        rollbackOn:
          format: date-time
          type: string
        createdOn:
          format: date-time
          type: string
        createdBy:
          type: string
        modifiedOn:
          format: date-time
          type: string
        modifiedBy:
          type: string
  securitySchemes:
    access_token:
      type: apiKey
      description: Token used to access storefront API.
      name: access_token
      in: query
