openapi: 3.2.0
info:
  version: storefront-v1
  title: Storefront API V1 Paymetric API
servers:
- url: https://dogfood.commerce.insitesandbox.com
security: []
tags:
- name: Paymetric
paths:
  /api/v1/paymetric/config:
    post:
      tags:
      - Paymetric
      operationId: PaymetricV1_GetConfigAsync
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
            text/json:
              schema:
                type: object
            application/xml:
              schema:
                type: object
            text/xml:
              schema:
                type: object
            text/html:
              schema:
                type: object
      security:
      - access_token: []
  /api/v1/paymetric/responsepacket:
    get:
      tags:
      - Paymetric
      operationId: PaymetricV1_GetResponsePacketAsync
      parameters:
      - name: accessToken
        in: query
        required: false
        schema:
          type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
            text/json:
              schema:
                type: object
            application/xml:
              schema:
                type: object
            text/xml:
              schema:
                type: object
            text/html:
              schema:
                type: object
      security:
      - access_token: []
components:
  securitySchemes:
    access_token:
      type: apiKey
      description: Token used to access storefront API.
      name: access_token
      in: query
