openapi: 3.2.0
info:
  version: admin-v1
  title: Admin API V1 Credit Card Transactions API
servers:
- url: https://dogfood.commerce.insitesandbox.com
security: []
tags:
- name: Credit Card Transactions
paths:
  /api/v1/admin/CreditCardTransactions:
    get:
      tags:
      - Credit Card Transactions
      summary: Returns the EntitySet CreditCardTransactions
      operationId: CreditCardTransactions_Get
      parameters:
      - name: $expand
        in: query
        description: Expands related entities inline.
        required: false
        schema:
          type: string
      - name: $filter
        in: query
        description: Filters the results, based on a Boolean condition.
        required: false
        schema:
          type: string
      - name: $select
        in: query
        description: Selects which properties to include in the response.
        required: false
        schema:
          type: string
      - name: $apply
        in: query
        description: Aggregates the results according to one or more transformations.
        required: false
        schema:
          type: string
      - name: $orderby
        in: query
        description: Sorts the results.
        required: false
        schema:
          type: string
      - name: $top
        in: query
        description: Returns only the first n results.
        required: false
        schema:
          type: integer
          format: int32
      - name: $skip
        in: query
        description: Skips the first n results.
        required: false
        schema:
          type: integer
          format: int32
      - name: $count
        in: query
        description: Includes a count of the matching results in the response.
        required: false
        schema:
          type: boolean
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                type: object
      deprecated: false
      security:
      - access_token: []
    post:
      tags:
      - Credit Card Transactions
      summary: Post a new entity to EntitySet CreditCardTransactions
      operationId: CreditCardTransactions_Post
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Insite.Data.Entities.CreditCardTransaction'
        description: The entity to post
        required: true
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                type: object
      deprecated: false
      security:
      - access_token: []
  /api/v1/admin/CreditCardTransactions({id}):
    get:
      tags:
      - Credit Card Transactions
      summary: Returns the entity with the key from CreditCardTransactions
      operationId: CreditCardTransactions_GetById
      parameters:
      - name: id
        in: path
        description: 'key: id'
        required: true
        schema:
          type: string
          format: uuid
      - name: $expand
        in: query
        description: Expands related entities inline.
        required: false
        schema:
          type: string
      - name: $select
        in: query
        description: Selects which properties to include in the response.
        required: false
        schema:
          type: string
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                type: object
      deprecated: false
      security:
      - access_token: []
    put:
      tags:
      - Credit Card Transactions
      summary: Replace entity in EntitySet CreditCardTransactions
      operationId: CreditCardTransactions_PutById
      parameters:
      - name: id
        in: path
        description: 'key: id'
        required: true
        schema:
          type: string
          format: uuid
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Insite.Data.Entities.CreditCardTransaction'
        description: The entity to put
        required: true
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                type: object
      deprecated: false
      security:
      - access_token: []
    delete:
      tags:
      - Credit Card Transactions
      summary: Delete entity in EntitySet CreditCardTransactions
      operationId: CreditCardTransactions_DeleteById
      parameters:
      - name: id
        in: path
        description: 'key: id'
        required: true
        schema:
          type: string
          format: uuid
      - name: If-Match
        in: header
        description: If-Match header
        required: false
        schema:
          type: string
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                type: object
      deprecated: false
      security:
      - access_token: []
    patch:
      tags:
      - Credit Card Transactions
      summary: Update entity in EntitySet CreditCardTransactions
      operationId: CreditCardTransactions_PatchById
      parameters:
      - name: id
        in: path
        description: 'key: id'
        required: true
        schema:
          type: string
          format: uuid
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Insite.Data.Entities.CreditCardTransaction'
        description: The entity to patch
        required: true
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                type: object
      deprecated: false
      security:
      - access_token: []
  /api/v1/admin/CreditCardTransactions/Default.Default():
    get:
      tags:
      - Credit Card Transactions
      summary: Call operation  Default
      operationId: CreditCardTransactions_Default
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                type: object
      deprecated: false
      security:
      - access_token: []
  /api/v1/admin/creditcardtransactions/delete:
    delete:
      tags:
      - Credit Card Transactions
      operationId: CreditCardTransactions_DeleteRoute
      parameters:
      - name: ids
        in: query
        required: true
        explode: true
        schema:
          type: array
          items:
            type: string
            format: uuid
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                type: object
      deprecated: false
      security:
      - access_token: []
  /api/v1/admin/creditcardtransactions({key})/customproperties({custompropertyKey}):
    get:
      tags:
      - Credit Card Transactions
      operationId: CreditCardTransactions_GetCustomPropertyByKeyAndCustompropertykey
      parameters:
      - name: key
        in: path
        required: true
        schema:
          type: string
          format: uuid
      - name: custompropertyKey
        in: path
        required: true
        schema:
          type: string
          format: uuid
      - name: $expand
        in: query
        description: Expands related entities inline.
        required: false
        schema:
          type: string
      - name: $select
        in: query
        description: Selects which properties to include in the response.
        required: false
        schema:
          type: string
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                type: object
      deprecated: false
      security:
      - access_token: []
components:
  schemas:
    Insite.Data.Entities.CreditCardTransaction:
      required:
      - transactionType
      - result
      - authCode
      - pnRef
      - respMsg
      - respText
      - avsAddr
      - avsZip
      - avsResponse
      - cvv2Match
      - requestId
      - requestString
      - responseString
      - status
      - creditCardNumber
      - name
      - expirationDate
      - orderNumber
      - shipmentNumber
      - customerNumber
      - site
      - origId
      - bankCode
      - cardType
      - invoiceNumber
      type: object
      properties:
        id:
          format: uuid
          type: string
          example: 00000000-0000-0000-0000-000000000000
        customerOrderId:
          format: uuid
          type: string
          example: 00000000-0000-0000-0000-000000000000
        transactionType:
          maxLength: 50
          minLength: 0
          type: string
        transactionDate:
          format: date-time
          type: string
        result:
          maxLength: 50
          minLength: 0
          type: string
        authCode:
          maxLength: 200
          minLength: 0
          type: string
        pnRef:
          maxLength: 256
          minLength: 0
          type: string
        respMsg:
          maxLength: 1024
          minLength: 0
          type: string
        respText:
          maxLength: 1024
          minLength: 0
          type: string
        avsAddr:
          maxLength: 250
          minLength: 0
          type: string
        avsZip:
          maxLength: 50
          minLength: 0
          type: string
        avsResponse:
          maxLength: 500
          minLength: 0
          type: string
        cvv2Match:
          maxLength: 50
          minLength: 0
          type: string
        requestId:
          maxLength: 100
          minLength: 0
          type: string
        requestString:
          type: string
        responseString:
          type: string
        amount:
          format: decimal
          type: number
        status:
          maxLength: 50
          minLength: 0
          type: string
        creditCardNumber:
          maxLength: 50
          minLength: 0
          type: string
        name:
          maxLength: 50
          minLength: 0
          type: string
        expirationDate:
          maxLength: 50
          minLength: 0
          type: string
        orderNumber:
          maxLength: 50
          minLength: 0
          type: string
        shipmentNumber:
          maxLength: 50
          minLength: 0
          type: string
        customerNumber:
          maxLength: 50
          minLength: 0
          type: string
        site:
          maxLength: 50
          minLength: 0
          type: string
        origId:
          maxLength: 100
          minLength: 0
          type: string
        bankCode:
          maxLength: 50
          minLength: 0
          type: string
        token1:
          maxLength: 200
          minLength: 0
          type: string
        token2:
          maxLength: 200
          minLength: 0
          type: string
        gatewayProfileId:
          maxLength: 200
          minLength: 0
          type: string
        cardType:
          maxLength: 200
          minLength: 0
          type: string
        postedToErp:
          type: boolean
        invoiceNumber:
          maxLength: 50
          minLength: 0
          type: string
        currencyId:
          format: uuid
          type: string
          example: 00000000-0000-0000-0000-000000000000
        currencyAmount:
          format: double
          type: number
        createdOn:
          format: date-time
          type: string
        createdBy:
          type: string
        modifiedOn:
          format: date-time
          type: string
        modifiedBy:
          type: string
  securitySchemes:
    access_token:
      type: apiKey
      description: Token used to access storefront API.
      name: access_token
      in: query
