openapi: 3.2.0
info:
  version: admin-v1
  title: Admin API V1 Integration Jobs API
servers:
- url: https://dogfood.commerce.insitesandbox.com
security: []
tags:
- name: Integration Jobs
paths:
  /api/v1/admin/IntegrationJobs:
    get:
      tags:
      - Integration Jobs
      summary: Returns the EntitySet IntegrationJobs
      operationId: IntegrationJobs_Get
      parameters:
      - name: $expand
        in: query
        description: Expands related entities inline.
        required: false
        schema:
          type: string
      - name: $filter
        in: query
        description: Filters the results, based on a Boolean condition.
        required: false
        schema:
          type: string
      - name: $select
        in: query
        description: Selects which properties to include in the response.
        required: false
        schema:
          type: string
      - name: $apply
        in: query
        description: Aggregates the results according to one or more transformations.
        required: false
        schema:
          type: string
      - name: $orderby
        in: query
        description: Sorts the results.
        required: false
        schema:
          type: string
      - name: $top
        in: query
        description: Returns only the first n results.
        required: false
        schema:
          type: integer
          format: int32
      - name: $skip
        in: query
        description: Skips the first n results.
        required: false
        schema:
          type: integer
          format: int32
      - name: $count
        in: query
        description: Includes a count of the matching results in the response.
        required: false
        schema:
          type: boolean
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                type: object
      deprecated: false
      security:
      - access_token: []
    post:
      tags:
      - Integration Jobs
      summary: Post a new entity to EntitySet IntegrationJobs
      operationId: IntegrationJobs_Post
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Insite.Data.Entities.IntegrationJob'
        description: The entity to post
        required: true
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                type: object
      deprecated: false
      security:
      - access_token: []
  /api/v1/admin/IntegrationJobs({id}):
    get:
      tags:
      - Integration Jobs
      summary: Returns the entity with the key from IntegrationJobs
      operationId: IntegrationJobs_GetById
      parameters:
      - name: id
        in: path
        description: 'key: id'
        required: true
        schema:
          type: string
          format: uuid
      - name: $expand
        in: query
        description: Expands related entities inline.
        required: false
        schema:
          type: string
      - name: $select
        in: query
        description: Selects which properties to include in the response.
        required: false
        schema:
          type: string
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                type: object
      deprecated: false
      security:
      - access_token: []
    put:
      tags:
      - Integration Jobs
      summary: Replace entity in EntitySet IntegrationJobs
      operationId: IntegrationJobs_PutById
      parameters:
      - name: id
        in: path
        description: 'key: id'
        required: true
        schema:
          type: string
          format: uuid
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Insite.Data.Entities.IntegrationJob'
        description: The entity to put
        required: true
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                type: object
      deprecated: false
      security:
      - access_token: []
    delete:
      tags:
      - Integration Jobs
      summary: Delete entity in EntitySet IntegrationJobs
      operationId: IntegrationJobs_DeleteById
      parameters:
      - name: id
        in: path
        description: 'key: id'
        required: true
        schema:
          type: string
          format: uuid
      - name: If-Match
        in: header
        description: If-Match header
        required: false
        schema:
          type: string
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                type: object
      deprecated: false
      security:
      - access_token: []
    patch:
      tags:
      - Integration Jobs
      summary: Update entity in EntitySet IntegrationJobs
      operationId: IntegrationJobs_PatchById
      parameters:
      - name: id
        in: path
        description: 'key: id'
        required: true
        schema:
          type: string
          format: uuid
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Insite.Data.Entities.IntegrationJob'
        description: The entity to patch
        required: true
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                type: object
      deprecated: false
      security:
      - access_token: []
  /api/v1/admin/IntegrationJobs/Default.Default():
    get:
      tags:
      - Integration Jobs
      summary: Call operation  Default
      operationId: IntegrationJobs_Default
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                type: object
      deprecated: false
      security:
      - access_token: []
  /api/v1/admin/integrationjobs/delete:
    delete:
      tags:
      - Integration Jobs
      operationId: IntegrationJobs_DeleteRoute
      parameters:
      - name: ids
        in: query
        required: true
        explode: true
        schema:
          type: array
          items:
            type: string
            format: uuid
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                type: object
      deprecated: false
      security:
      - access_token: []
  /api/v1/admin/integrationjobs({key})/customproperties({custompropertyKey}):
    get:
      tags:
      - Integration Jobs
      operationId: IntegrationJobs_GetCustomPropertyByKeyAndCustompropertykey
      parameters:
      - name: key
        in: path
        required: true
        schema:
          type: string
          format: uuid
      - name: custompropertyKey
        in: path
        required: true
        schema:
          type: string
          format: uuid
      - name: $expand
        in: query
        description: Expands related entities inline.
        required: false
        schema:
          type: string
      - name: $select
        in: query
        description: Selects which properties to include in the response.
        required: false
        schema:
          type: string
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                type: object
      deprecated: false
      security:
      - access_token: []
  /api/v1/admin/integrationjobs({key})/integrationjoblogs({integrationjoblogKey}):
    get:
      tags:
      - Integration Jobs
      operationId: IntegrationJobs_GetIntegrationJobLogByKeyAndIntegrationjoblogkey
      parameters:
      - name: key
        in: path
        required: true
        schema:
          type: string
          format: uuid
      - name: integrationjoblogKey
        in: path
        required: true
        schema:
          type: string
          format: uuid
      - name: $expand
        in: query
        description: Expands related entities inline.
        required: false
        schema:
          type: string
      - name: $select
        in: query
        description: Selects which properties to include in the response.
        required: false
        schema:
          type: string
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                type: object
      deprecated: false
      security:
      - access_token: []
  /api/v1/admin/integrationjobs({key})/integrationjobparameters({integrationjobparameterKey}):
    get:
      tags:
      - Integration Jobs
      operationId: IntegrationJobs_GetIntegrationJobParameterByKeyAndIntegrationjobparameterkey
      parameters:
      - name: key
        in: path
        required: true
        schema:
          type: string
          format: uuid
      - name: integrationjobparameterKey
        in: path
        required: true
        schema:
          type: string
          format: uuid
      - name: $expand
        in: query
        description: Expands related entities inline.
        required: false
        schema:
          type: string
      - name: $select
        in: query
        description: Selects which properties to include in the response.
        required: false
        schema:
          type: string
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                type: object
      deprecated: false
      security:
      - access_token: []
components:
  schemas:
    Insite.Data.Entities.IntegrationJob:
      required:
      - status
      - notes
      - resultData
      - initialData
      - datasetFileLocation
      - exportObject
      - exportQuery
      - exportColumnList
      - siteUrl
      type: object
      properties:
        id:
          format: uuid
          type: string
          example: 00000000-0000-0000-0000-000000000000
        jobDefinitionId:
          format: uuid
          type: string
          example: 00000000-0000-0000-0000-000000000000
        startDateTime:
          format: date-time
          type: string
        endDateTime:
          format: date-time
          type: string
        duration:
          format: decimal
          type: number
        status:
          maxLength: 255
          minLength: 0
          type: string
        recordCount:
          format: int32
          type: integer
        notes:
          type: string
        dataSize:
          format: decimal
          type: number
        isRealTime:
          type: boolean
        resultData:
          type: string
        isPreview:
          type: boolean
        jobNumber:
          format: int32
          type: integer
        deltaDataSetProcessed:
          type: boolean
        scheduleDateTime:
          format: date-time
          type: string
        previewStepSequence:
          format: int32
          type: integer
        fileProcessed:
          type: boolean
        runStandalone:
          type: boolean
        warningCount:
          format: int32
          type: integer
        errorCount:
          format: int32
          type: integer
        datasetFileLocation:
          maxLength: 255
          minLength: 0
          type: string
        retryCounter:
          format: int32
          type: integer
        retryStartingFrom:
          format: int32
          type: integer
        recordsAdded:
          format: int32
          type: integer
        recordsModified:
          format: int32
          type: integer
        recordsDeleted:
          format: int32
          type: integer
        isActive:
          type: boolean
        exportObject:
          type: string
        exportQuery:
          type: string
        exportColumnList:
          type: string
        siteUrl:
          type: string
        websiteId:
          format: uuid
          type: string
          example: 00000000-0000-0000-0000-000000000000
        host:
          type: string
        createdOn:
          format: date-time
          type: string
        createdBy:
          type: string
        modifiedOn:
          format: date-time
          type: string
        modifiedBy:
          type: string
        initialData:
          type: string
  securitySchemes:
    access_token:
      type: apiKey
      description: Token used to access storefront API.
      name: access_token
      in: query
