openapi: 3.2.0
info:
  version: admin-v1
  title: Admin API V1 Order Histories API
servers:
- url: https://dogfood.commerce.insitesandbox.com
security: []
tags:
- name: Order Histories
paths:
  /api/v1/admin/OrderHistories:
    get:
      tags:
      - Order Histories
      summary: Returns the EntitySet OrderHistories
      operationId: OrderHistories_Get
      parameters:
      - name: $expand
        in: query
        description: Expands related entities inline.
        required: false
        schema:
          type: string
      - name: $filter
        in: query
        description: Filters the results, based on a Boolean condition.
        required: false
        schema:
          type: string
      - name: $select
        in: query
        description: Selects which properties to include in the response.
        required: false
        schema:
          type: string
      - name: $apply
        in: query
        description: Aggregates the results according to one or more transformations.
        required: false
        schema:
          type: string
      - name: $orderby
        in: query
        description: Sorts the results.
        required: false
        schema:
          type: string
      - name: $top
        in: query
        description: Returns only the first n results.
        required: false
        schema:
          type: integer
          format: int32
      - name: $skip
        in: query
        description: Skips the first n results.
        required: false
        schema:
          type: integer
          format: int32
      - name: $count
        in: query
        description: Includes a count of the matching results in the response.
        required: false
        schema:
          type: boolean
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                type: object
      deprecated: false
      security:
      - access_token: []
    post:
      tags:
      - Order Histories
      summary: Post a new entity to EntitySet OrderHistories
      operationId: OrderHistories_Post
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Insite.Data.Entities.OrderHistory'
        description: The entity to post
        required: true
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                type: object
      deprecated: false
      security:
      - access_token: []
  /api/v1/admin/OrderHistories({id}):
    get:
      tags:
      - Order Histories
      summary: Returns the entity with the key from OrderHistories
      operationId: OrderHistories_GetById
      parameters:
      - name: id
        in: path
        description: 'key: id'
        required: true
        schema:
          type: string
          format: uuid
      - name: $expand
        in: query
        description: Expands related entities inline.
        required: false
        schema:
          type: string
      - name: $select
        in: query
        description: Selects which properties to include in the response.
        required: false
        schema:
          type: string
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                type: object
      deprecated: false
      security:
      - access_token: []
    put:
      tags:
      - Order Histories
      summary: Replace entity in EntitySet OrderHistories
      operationId: OrderHistories_PutById
      parameters:
      - name: id
        in: path
        description: 'key: id'
        required: true
        schema:
          type: string
          format: uuid
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Insite.Data.Entities.OrderHistory'
        description: The entity to put
        required: true
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                type: object
      deprecated: false
      security:
      - access_token: []
    delete:
      tags:
      - Order Histories
      summary: Delete entity in EntitySet OrderHistories
      operationId: OrderHistories_DeleteById
      parameters:
      - name: id
        in: path
        description: 'key: id'
        required: true
        schema:
          type: string
          format: uuid
      - name: If-Match
        in: header
        description: If-Match header
        required: false
        schema:
          type: string
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                type: object
      deprecated: false
      security:
      - access_token: []
    patch:
      tags:
      - Order Histories
      summary: Update entity in EntitySet OrderHistories
      operationId: OrderHistories_PatchById
      parameters:
      - name: id
        in: path
        description: 'key: id'
        required: true
        schema:
          type: string
          format: uuid
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Insite.Data.Entities.OrderHistory'
        description: The entity to patch
        required: true
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                type: object
      deprecated: false
      security:
      - access_token: []
  /api/v1/admin/OrderHistories/Default.Default():
    get:
      tags:
      - Order Histories
      summary: Call operation  Default
      operationId: OrderHistories_Default
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                type: object
      deprecated: false
      security:
      - access_token: []
  /api/v1/admin/orderhistories/delete:
    delete:
      tags:
      - Order Histories
      operationId: OrderHistories_DeleteRoute
      parameters:
      - name: ids
        in: query
        required: true
        explode: true
        schema:
          type: array
          items:
            type: string
            format: uuid
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                type: object
      deprecated: false
      security:
      - access_token: []
  /api/v1/admin/orderhistories({key})/customproperties({custompropertyKey}):
    get:
      tags:
      - Order Histories
      operationId: OrderHistories_GetCustomPropertyByKeyAndCustompropertykey
      parameters:
      - name: key
        in: path
        required: true
        schema:
          type: string
          format: uuid
      - name: custompropertyKey
        in: path
        required: true
        schema:
          type: string
          format: uuid
      - name: $expand
        in: query
        description: Expands related entities inline.
        required: false
        schema:
          type: string
      - name: $select
        in: query
        description: Selects which properties to include in the response.
        required: false
        schema:
          type: string
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                type: object
      deprecated: false
      security:
      - access_token: []
  /api/v1/admin/orderhistories({key})/orderhistorylines({orderhistorylineKey}):
    get:
      tags:
      - Order Histories
      operationId: OrderHistories_GetOrderHistoryLineByKeyAndOrderhistorylinekey
      parameters:
      - name: key
        in: path
        required: true
        schema:
          type: string
          format: uuid
      - name: orderhistorylineKey
        in: path
        required: true
        schema:
          type: string
          format: uuid
      - name: $expand
        in: query
        description: Expands related entities inline.
        required: false
        schema:
          type: string
      - name: $select
        in: query
        description: Selects which properties to include in the response.
        required: false
        schema:
          type: string
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                type: object
      deprecated: false
      security:
      - access_token: []
  /api/v1/admin/orderhistories({key})/orderhistorypromotions({orderhistorypromotionKey}):
    get:
      tags:
      - Order Histories
      operationId: OrderHistories_GetOrderHistoryPromotionByKeyAndOrderhistorypromotionkey
      parameters:
      - name: key
        in: path
        required: true
        schema:
          type: string
          format: uuid
      - name: orderhistorypromotionKey
        in: path
        required: true
        schema:
          type: string
          format: uuid
      - name: $expand
        in: query
        description: Expands related entities inline.
        required: false
        schema:
          type: string
      - name: $select
        in: query
        description: Selects which properties to include in the response.
        required: false
        schema:
          type: string
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                type: object
      deprecated: false
      security:
      - access_token: []
  /api/v1/admin/orderhistories({key})/orderhistorytaxes({orderhistorytaxKey}):
    get:
      tags:
      - Order Histories
      operationId: OrderHistories_GetOrderHistoryTaxByKeyAndOrderhistorytaxkey
      parameters:
      - name: key
        in: path
        required: true
        schema:
          type: string
          format: uuid
      - name: orderhistorytaxKey
        in: path
        required: true
        schema:
          type: string
          format: uuid
      - name: $expand
        in: query
        description: Expands related entities inline.
        required: false
        schema:
          type: string
      - name: $select
        in: query
        description: Selects which properties to include in the response.
        required: false
        schema:
          type: string
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                type: object
      deprecated: false
      security:
      - access_token: []
components:
  schemas:
    Insite.Data.Entities.OrderHistory:
      required:
      - erpOrderNumber
      - webOrderNumber
      - status
      - customerNumber
      - customerSequence
      - customerPO
      - currencyCode
      - terms
      - shipCode
      - salesperson
      - btCompanyName
      - btAddress1
      - btAddress2
      - btAddress3
      - btAddress4
      - btCity
      - btState
      - btPostalCode
      - btCountry
      - stCompanyName
      - stAddress1
      - stAddress2
      - stAddress3
      - stAddress4
      - stCity
      - stState
      - stPostalCode
      - stCountry
      - notes
      - fulfillmentMethod
      - customerVatNumber
      - vmiLocationName
      - orderSource
      - orderDeviceType
      type: object
      properties:
        id:
          format: uuid
          type: string
          example: 00000000-0000-0000-0000-000000000000
        erpOrderNumber:
          maxLength: 50
          minLength: 0
          type: string
        webOrderNumber:
          maxLength: 50
          minLength: 0
          type: string
        orderDate:
          format: date-time
          type: string
        status:
          maxLength: 50
          minLength: 0
          type: string
        customerNumber:
          maxLength: 50
          minLength: 0
          type: string
        customerSequence:
          maxLength: 50
          minLength: 0
          type: string
        customerPO:
          maxLength: 50
          minLength: 0
          type: string
        currencyCode:
          maxLength: 50
          minLength: 0
          type: string
        terms:
          maxLength: 50
          minLength: 0
          type: string
        shipCode:
          maxLength: 50
          minLength: 0
          type: string
        salesperson:
          maxLength: 50
          minLength: 0
          type: string
        btCompanyName:
          maxLength: 100
          minLength: 0
          type: string
        btAddress1:
          maxLength: 100
          minLength: 0
          type: string
        btAddress2:
          maxLength: 100
          minLength: 0
          type: string
        btAddress3:
          maxLength: 100
          minLength: 0
          type: string
        btAddress4:
          maxLength: 100
          minLength: 0
          type: string
        btCity:
          maxLength: 100
          minLength: 0
          type: string
        btState:
          maxLength: 50
          minLength: 0
          type: string
        btPostalCode:
          maxLength: 50
          minLength: 0
          type: string
        btCountry:
          maxLength: 100
          minLength: 0
          type: string
        stCompanyName:
          maxLength: 100
          minLength: 0
          type: string
        stAddress1:
          maxLength: 100
          minLength: 0
          type: string
        stAddress2:
          maxLength: 100
          minLength: 0
          type: string
        stAddress3:
          maxLength: 100
          minLength: 0
          type: string
        stAddress4:
          maxLength: 100
          minLength: 0
          type: string
        stCity:
          maxLength: 100
          minLength: 0
          type: string
        stState:
          maxLength: 50
          minLength: 0
          type: string
        stPostalCode:
          maxLength: 50
          minLength: 0
          type: string
        stCountry:
          maxLength: 100
          minLength: 0
          type: string
        notes:
          type: string
        productTotal:
          format: decimal
          type: number
        orderDiscountAmount:
          format: decimal
          type: number
        productDiscountAmount:
          format: decimal
          type: number
        shippingCharges:
          format: decimal
          type: number
        handlingCharges:
          format: decimal
          type: number
        otherCharges:
          format: decimal
          type: number
        taxAmount:
          format: decimal
          type: number
        orderTotal:
          format: decimal
          type: number
        conversionRate:
          format: double
          type: number
        requestedDeliveryDate:
          format: date-time
          type: string
        impersonatedByAdminUserProfileId:
          format: uuid
          type: string
          example: 00000000-0000-0000-0000-000000000000
        isGuestOrder:
          type: boolean
        fulfillmentMethod:
          maxLength: 50
          minLength: 0
          type: string
        customerVatNumber:
          maxLength: 50
          minLength: 0
          type: string
        shippingVatAmount:
          format: decimal
          type: number
        vmiLocationId:
          format: uuid
          type: string
          example: 00000000-0000-0000-0000-000000000000
        vmiLocationName:
          maxLength: 255
          minLength: 0
          type: string
        orderSource:
          maxLength: 50
          minLength: 0
          type: string
        orderDeviceType:
          maxLength: 50
          minLength: 0
          type: string
        createdOn:
          format: date-time
          type: string
        createdBy:
          type: string
        modifiedOn:
          format: date-time
          type: string
        modifiedBy:
          type: string
  securitySchemes:
    access_token:
      type: apiKey
      description: Token used to access storefront API.
      name: access_token
      in: query
