openapi: 3.2.0
info:
  version: admin-v1
  title: Admin API V1 Punch Out Order Requests API
servers:
- url: https://dogfood.commerce.insitesandbox.com
security: []
tags:
- name: Punch Out Order Requests
paths:
  /api/v1/admin/PunchOutOrderRequests:
    get:
      tags:
      - Punch Out Order Requests
      summary: Returns the EntitySet PunchOutOrderRequests
      operationId: PunchOutOrderRequests_Get
      parameters:
      - name: $expand
        in: query
        description: Expands related entities inline.
        required: false
        schema:
          type: string
      - name: $filter
        in: query
        description: Filters the results, based on a Boolean condition.
        required: false
        schema:
          type: string
      - name: $select
        in: query
        description: Selects which properties to include in the response.
        required: false
        schema:
          type: string
      - name: $apply
        in: query
        description: Aggregates the results according to one or more transformations.
        required: false
        schema:
          type: string
      - name: $orderby
        in: query
        description: Sorts the results.
        required: false
        schema:
          type: string
      - name: $top
        in: query
        description: Returns only the first n results.
        required: false
        schema:
          type: integer
          format: int32
      - name: $skip
        in: query
        description: Skips the first n results.
        required: false
        schema:
          type: integer
          format: int32
      - name: $count
        in: query
        description: Includes a count of the matching results in the response.
        required: false
        schema:
          type: boolean
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                type: object
      deprecated: false
      security:
      - access_token: []
    post:
      tags:
      - Punch Out Order Requests
      summary: Post a new entity to EntitySet PunchOutOrderRequests
      operationId: PunchOutOrderRequests_Post
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Insite.Data.Entities.PunchOutOrderRequest'
        description: The entity to post
        required: true
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                type: object
      deprecated: false
      security:
      - access_token: []
  /api/v1/admin/PunchOutOrderRequests({id}):
    get:
      tags:
      - Punch Out Order Requests
      summary: Returns the entity with the key from PunchOutOrderRequests
      operationId: PunchOutOrderRequests_GetById
      parameters:
      - name: id
        in: path
        description: 'key: id'
        required: true
        schema:
          type: string
          format: uuid
      - name: $expand
        in: query
        description: Expands related entities inline.
        required: false
        schema:
          type: string
      - name: $select
        in: query
        description: Selects which properties to include in the response.
        required: false
        schema:
          type: string
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                type: object
      deprecated: false
      security:
      - access_token: []
    put:
      tags:
      - Punch Out Order Requests
      summary: Replace entity in EntitySet PunchOutOrderRequests
      operationId: PunchOutOrderRequests_PutById
      parameters:
      - name: id
        in: path
        description: 'key: id'
        required: true
        schema:
          type: string
          format: uuid
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Insite.Data.Entities.PunchOutOrderRequest'
        description: The entity to put
        required: true
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                type: object
      deprecated: false
      security:
      - access_token: []
    delete:
      tags:
      - Punch Out Order Requests
      summary: Delete entity in EntitySet PunchOutOrderRequests
      operationId: PunchOutOrderRequests_DeleteById
      parameters:
      - name: id
        in: path
        description: 'key: id'
        required: true
        schema:
          type: string
          format: uuid
      - name: If-Match
        in: header
        description: If-Match header
        required: false
        schema:
          type: string
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                type: object
      deprecated: false
      security:
      - access_token: []
    patch:
      tags:
      - Punch Out Order Requests
      summary: Update entity in EntitySet PunchOutOrderRequests
      operationId: PunchOutOrderRequests_PatchById
      parameters:
      - name: id
        in: path
        description: 'key: id'
        required: true
        schema:
          type: string
          format: uuid
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Insite.Data.Entities.PunchOutOrderRequest'
        description: The entity to patch
        required: true
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                type: object
      deprecated: false
      security:
      - access_token: []
  /api/v1/admin/PunchOutOrderRequests/Default.Default():
    get:
      tags:
      - Punch Out Order Requests
      summary: Call operation  Default
      operationId: PunchOutOrderRequests_Default
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                type: object
      deprecated: false
      security:
      - access_token: []
  /api/v1/admin/punchoutorderrequests/delete:
    delete:
      tags:
      - Punch Out Order Requests
      operationId: PunchOutOrderRequests_DeleteRoute
      parameters:
      - name: ids
        in: query
        required: true
        explode: true
        schema:
          type: array
          items:
            type: string
            format: uuid
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                type: object
      deprecated: false
      security:
      - access_token: []
  /api/v1/admin/punchoutorderrequests({key})/customproperties({custompropertyKey}):
    get:
      tags:
      - Punch Out Order Requests
      operationId: PunchOutOrderRequests_GetCustomPropertyByKeyAndCustompropertykey
      parameters:
      - name: key
        in: path
        required: true
        schema:
          type: string
          format: uuid
      - name: custompropertyKey
        in: path
        required: true
        schema:
          type: string
          format: uuid
      - name: $expand
        in: query
        description: Expands related entities inline.
        required: false
        schema:
          type: string
      - name: $select
        in: query
        description: Selects which properties to include in the response.
        required: false
        schema:
          type: string
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                type: object
      deprecated: false
      security:
      - access_token: []
  /api/v1/admin/punchoutorderrequests({key})/punchoutorderrequestextrinsics({punchoutorderrequestextrinsicKey}):
    get:
      tags:
      - Punch Out Order Requests
      operationId: PunchOutOrderRequests_GetPunchOutOrderRequestExtrinsicByKeyAndPunchoutorderrequestextrinsickey
      parameters:
      - name: key
        in: path
        required: true
        schema:
          type: string
          format: uuid
      - name: punchoutorderrequestextrinsicKey
        in: path
        required: true
        schema:
          type: string
          format: uuid
      - name: $expand
        in: query
        description: Expands related entities inline.
        required: false
        schema:
          type: string
      - name: $select
        in: query
        description: Selects which properties to include in the response.
        required: false
        schema:
          type: string
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                type: object
      deprecated: false
      security:
      - access_token: []
  /api/v1/admin/punchoutorderrequests({key})/punchoutorderrequestitemouts({punchoutorderrequestitemoutKey}):
    get:
      tags:
      - Punch Out Order Requests
      operationId: PunchOutOrderRequests_GetPunchOutOrderRequestItemOutByKeyAndPunchoutorderrequestitemoutkey
      parameters:
      - name: key
        in: path
        required: true
        schema:
          type: string
          format: uuid
      - name: punchoutorderrequestitemoutKey
        in: path
        required: true
        schema:
          type: string
          format: uuid
      - name: $expand
        in: query
        description: Expands related entities inline.
        required: false
        schema:
          type: string
      - name: $select
        in: query
        description: Selects which properties to include in the response.
        required: false
        schema:
          type: string
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                type: object
      deprecated: false
      security:
      - access_token: []
  /api/v1/admin/punchoutorderrequests({key})/punchoutorderrequestmessages({punchoutorderrequestmessageKey}):
    get:
      tags:
      - Punch Out Order Requests
      operationId: PunchOutOrderRequests_GetPunchOutOrderRequestMessageByKeyAndPunchoutorderrequestmessagekey
      parameters:
      - name: key
        in: path
        required: true
        schema:
          type: string
          format: uuid
      - name: punchoutorderrequestmessageKey
        in: path
        required: true
        schema:
          type: string
          format: uuid
      - name: $expand
        in: query
        description: Expands related entities inline.
        required: false
        schema:
          type: string
      - name: $select
        in: query
        description: Selects which properties to include in the response.
        required: false
        schema:
          type: string
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                type: object
      deprecated: false
      security:
      - access_token: []
components:
  schemas:
    Insite.Data.Entities.PunchOutOrderRequest:
      required:
      - fromIdentity
      - toIdentity
      - senderIdentity
      - fromUserAgent
      - orderId
      - orderDate
      - orderType
      - orderVersion
      - isInternalVersion
      - agreementId
      - agreementPayloadId
      - parentAgreementId
      - parentAgreementPayloadId
      - effectiveDate
      - expirationDate
      - requisitionId
      - shipComplete
      - releaseRequired
      - type
      - punchOutOrderRequestCXml
      - total
      - totalCurrency
      - shipping
      - shippingCurrency
      - shippingDescription
      - billToAddressId
      - billToName
      - billToStreet
      - billToCity
      - billToState
      - billToPostalCode
      - billToIsoCountryCode
      - billToCountry
      - shipToAddressId
      - shipToName
      - shipToStreet
      - shipToCity
      - shipToState
      - shipToPostalCode
      - shipToIsoCountryCode
      - shipToCountry
      - billToDeliver1
      - shipToDeliver1
      - shipToDeliver2
      - billToDeliver2
      - comments
      - billToEmail
      - shipToEmail
      - billToStreet2
      - billToStreet3
      - billToStreet4
      - billToTelephoneNumber
      - billToTelephoneIsoCountryCode
      - billToTelephoneAreaOrCityCode
      - shipToStreet2
      - shipToStreet3
      - shipToStreet4
      - shipToTelephoneNumber
      - shipToTelephoneIsoCountryCode
      - shipToTelephoneAreaOrCityCode
      - billToTelephoneCountryCode
      - shipToTelephoneCountryCode
      - orderResponse
      - customerPo
      - status
      type: object
      properties:
        id:
          format: uuid
          type: string
          example: 00000000-0000-0000-0000-000000000000
        fromIdentity:
          maxLength: 256
          minLength: 0
          type: string
        toIdentity:
          maxLength: 256
          minLength: 0
          type: string
        senderIdentity:
          maxLength: 256
          minLength: 0
          type: string
        fromUserAgent:
          maxLength: 512
          minLength: 0
          type: string
        orderId:
          maxLength: 256
          minLength: 0
          type: string
        orderDate:
          maxLength: 128
          minLength: 0
          type: string
        orderType:
          maxLength: 64
          minLength: 0
          type: string
        orderVersion:
          maxLength: 64
          minLength: 0
          type: string
        isInternalVersion:
          maxLength: 50
          minLength: 0
          type: string
        agreementId:
          maxLength: 64
          minLength: 0
          type: string
        agreementPayloadId:
          maxLength: 64
          minLength: 0
          type: string
        parentAgreementId:
          maxLength: 64
          minLength: 0
          type: string
        parentAgreementPayloadId:
          maxLength: 64
          minLength: 0
          type: string
        effectiveDate:
          maxLength: 64
          minLength: 0
          type: string
        expirationDate:
          maxLength: 64
          minLength: 0
          type: string
        requisitionId:
          maxLength: 64
          minLength: 0
          type: string
        shipComplete:
          maxLength: 50
          minLength: 0
          type: string
        releaseRequired:
          maxLength: 50
          minLength: 0
          type: string
        type:
          maxLength: 64
          minLength: 0
          type: string
        punchOutOrderRequestCXml:
          type: string
        total:
          maxLength: 50
          minLength: 0
          type: string
        totalCurrency:
          maxLength: 50
          minLength: 0
          type: string
        shipping:
          maxLength: 50
          minLength: 0
          type: string
        shippingCurrency:
          maxLength: 50
          minLength: 0
          type: string
        shippingDescription:
          maxLength: 1024
          minLength: 0
          type: string
        billToAddressId:
          maxLength: 50
          minLength: 0
          type: string
        billToName:
          maxLength: 512
          minLength: 0
          type: string
        billToStreet:
          maxLength: 256
          minLength: 0
          type: string
        billToCity:
          maxLength: 128
          minLength: 0
          type: string
        billToState:
          maxLength: 128
          minLength: 0
          type: string
        billToPostalCode:
          maxLength: 50
          minLength: 0
          type: string
        billToIsoCountryCode:
          maxLength: 50
          minLength: 0
          type: string
        billToCountry:
          maxLength: 128
          minLength: 0
          type: string
        shipToAddressId:
          maxLength: 50
          minLength: 0
          type: string
        shipToName:
          maxLength: 512
          minLength: 0
          type: string
        shipToStreet:
          maxLength: 256
          minLength: 0
          type: string
        shipToCity:
          maxLength: 128
          minLength: 0
          type: string
        shipToState:
          maxLength: 128
          minLength: 0
          type: string
        shipToPostalCode:
          maxLength: 50
          minLength: 0
          type: string
        shipToIsoCountryCode:
          maxLength: 50
          minLength: 0
          type: string
        shipToCountry:
          maxLength: 128
          minLength: 0
          type: string
        billToDeliver1:
          maxLength: 128
          minLength: 0
          type: string
        shipToDeliver1:
          maxLength: 128
          minLength: 0
          type: string
        shipToDeliver2:
          maxLength: 128
          minLength: 0
          type: string
        billToDeliver2:
          maxLength: 128
          minLength: 0
          type: string
        comments:
          type: string
        billToEmail:
          maxLength: 1024
          minLength: 0
          type: string
        shipToEmail:
          maxLength: 1024
          minLength: 0
          type: string
        requestUrl:
          type: string
        customerOrderId:
          format: uuid
          type: string
          example: 00000000-0000-0000-0000-000000000000
        userProfileId:
          format: uuid
          type: string
          example: 00000000-0000-0000-0000-000000000000
        billToStreet2:
          maxLength: 1024
          minLength: 0
          type: string
        billToStreet3:
          maxLength: 1024
          minLength: 0
          type: string
        billToStreet4:
          maxLength: 1024
          minLength: 0
          type: string
        billToTelephoneNumber:
          maxLength: 50
          minLength: 0
          type: string
        billToTelephoneIsoCountryCode:
          maxLength: 50
          minLength: 0
          type: string
        billToTelephoneAreaOrCityCode:
          maxLength: 50
          minLength: 0
          type: string
        shipToStreet2:
          maxLength: 100
          minLength: 0
          type: string
        shipToStreet3:
          maxLength: 100
          minLength: 0
          type: string
        shipToStreet4:
          maxLength: 100
          minLength: 0
          type: string
        shipToTelephoneNumber:
          maxLength: 50
          minLength: 0
          type: string
        shipToTelephoneIsoCountryCode:
          maxLength: 50
          minLength: 0
          type: string
        shipToTelephoneAreaOrCityCode:
          maxLength: 50
          minLength: 0
          type: string
        punchOutSessionId:
          format: uuid
          type: string
          example: 00000000-0000-0000-0000-000000000000
        billToTelephoneCountryCode:
          maxLength: 5
          minLength: 0
          type: string
        shipToTelephoneCountryCode:
          maxLength: 5
          minLength: 0
          type: string
        orderResponse:
          type: string
        customerPo:
          maxLength: 256
          minLength: 0
          type: string
        status:
          maxLength: 256
          minLength: 0
          type: string
        createdOn:
          format: date-time
          type: string
        createdBy:
          type: string
        modifiedOn:
          format: date-time
          type: string
        modifiedBy:
          type: string
  securitySchemes:
    access_token:
      type: apiKey
      description: Token used to access storefront API.
      name: access_token
      in: query
