openapi: 3.2.0
info:
  title: Optimizely Agent Lookup API
  description: Optimizely Agent is a stand-alone, open-source microservice that provides major benefits over using Optimizely SDKs in certain use cases. Its REST API offers consolidated and simplified endpoints for accessing all the functionality of Optimizely Feature Experimentation SDKs. Use this API the control experiments (such as a feature tests). For more info, see https://docs.developers.optimizely.com/experimentation/v4.0.0-full-stack/docs/optimizely-agent
  termsOfService: https://www.optimizely.com/legal/terms/
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
  version: 0.12.0
security:
- SdkKeyAuth: []
- TokenAuth: []
tags:
- name: Lookup
paths:
  /v1/lookup:
    post:
      summary: Lookup returns saved user profile.
      description: Returns the saved user profile for a user.
      operationId: lookup
      requestBody:
        description: ''
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LookupContext'
        required: true
      responses:
        '200':
          description: Valid response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserProfile'
        '400':
          description: Missing required parameters
          content:
            application/json: {}
        '401':
          description: Unauthorized, invalid JWT
          content:
            application/json: {}
        '403':
          description: You do not have necessary permissions for the resource
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: User Profile Service not found
          content:
            application/json: {}
      deprecated: false
      tags:
      - Lookup
components:
  schemas:
    Error:
      title: Error
      type: object
      properties:
        error:
          type: string
    ExperimentBucketMap:
      title: ExperimentBucketMap
      type: object
      properties:
        your_experiment_id:
          $ref: '#/components/schemas/YourExperimentId'
    LookupContext:
      title: LookupContext
      required:
      - userId
      type: object
      properties:
        userId:
          type: string
    UserProfile:
      title: UserProfile
      type: object
      properties:
        experimentBucketMap:
          $ref: '#/components/schemas/ExperimentBucketMap'
        userId:
          type: string
    YourExperimentId:
      title: YourExperimentId
      type: object
      properties:
        variation_id:
          type: string
  securitySchemes:
    SdkKeyAuth:
      type: apiKey
      name: X-Optimizely-SDK-Key
      in: header
    TokenAuth:
      type: http
      scheme: bearer
      bearerFormat: jwt
x-readme:
  explorer-enabled: true
  proxy-enabled: true
