openapi: 3.2.0
info:
  version: storefront-v1
  title: Storefront API V1 Email API
servers:
- url: https://dogfood.commerce.insitesandbox.com
security: []
tags:
- name: Email
paths:
  /api/v1/email:
    get:
      tags:
      - Email
      operationId: EmailV1_Get
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/System.Web.Http.Results.OkResult'
            text/json:
              schema:
                $ref: '#/components/schemas/System.Web.Http.Results.OkResult'
            text/html:
              schema:
                $ref: '#/components/schemas/System.Web.Http.Results.OkResult'
  /api/v1/email/tellafriend:
    post:
      tags:
      - Email
      operationId: EmailV1_PostTellAFriend
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Insite.Email.WebApi.V1.ApiModels.TellAFriendModel'
          text/json:
            schema:
              $ref: '#/components/schemas/Insite.Email.WebApi.V1.ApiModels.TellAFriendModel'
          application/xml:
            schema:
              $ref: '#/components/schemas/Insite.Email.WebApi.V1.ApiModels.TellAFriendModel'
          text/xml:
            schema:
              $ref: '#/components/schemas/Insite.Email.WebApi.V1.ApiModels.TellAFriendModel'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Insite.Email.WebApi.V1.ApiModels.TellAFriendModel'
          text/html:
            schema:
              $ref: '#/components/schemas/Insite.Email.WebApi.V1.ApiModels.TellAFriendModel'
        required: true
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Insite.Email.WebApi.V1.ApiModels.TellAFriendModel'
            text/json:
              schema:
                $ref: '#/components/schemas/Insite.Email.WebApi.V1.ApiModels.TellAFriendModel'
            application/xml:
              schema:
                $ref: '#/components/schemas/Insite.Email.WebApi.V1.ApiModels.TellAFriendModel'
            text/xml:
              schema:
                $ref: '#/components/schemas/Insite.Email.WebApi.V1.ApiModels.TellAFriendModel'
            text/html:
              schema:
                $ref: '#/components/schemas/Insite.Email.WebApi.V1.ApiModels.TellAFriendModel'
  /api/v1/email/contactUs:
    post:
      tags:
      - Email
      operationId: EmailV1_PostContactUs
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Insite.Email.WebApi.V1.ApiModels.ContactUsModel'
          text/json:
            schema:
              $ref: '#/components/schemas/Insite.Email.WebApi.V1.ApiModels.ContactUsModel'
          application/xml:
            schema:
              $ref: '#/components/schemas/Insite.Email.WebApi.V1.ApiModels.ContactUsModel'
          text/xml:
            schema:
              $ref: '#/components/schemas/Insite.Email.WebApi.V1.ApiModels.ContactUsModel'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Insite.Email.WebApi.V1.ApiModels.ContactUsModel'
          text/html:
            schema:
              $ref: '#/components/schemas/Insite.Email.WebApi.V1.ApiModels.ContactUsModel'
        required: true
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Insite.Email.WebApi.V1.ApiModels.ContactUsModel'
            text/json:
              schema:
                $ref: '#/components/schemas/Insite.Email.WebApi.V1.ApiModels.ContactUsModel'
            application/xml:
              schema:
                $ref: '#/components/schemas/Insite.Email.WebApi.V1.ApiModels.ContactUsModel'
            text/xml:
              schema:
                $ref: '#/components/schemas/Insite.Email.WebApi.V1.ApiModels.ContactUsModel'
            text/html:
              schema:
                $ref: '#/components/schemas/Insite.Email.WebApi.V1.ApiModels.ContactUsModel'
components:
  schemas:
    Insite.Email.WebApi.V1.ApiModels.ContactUsModel:
      type: object
      properties:
        uri:
          type: string
        firstName:
          type: string
        lastName:
          type: string
        message:
          type: string
        topic:
          type: string
        phoneNumber:
          type: string
        emailAddress:
          type: string
        emailTo:
          type: string
        properties:
          type: object
          additionalProperties:
            type: string
    System.Web.Http.Results.OkResult:
      type: object
      properties:
        request:
          type: string
          readOnly: true
    Insite.Email.WebApi.V1.ApiModels.TellAFriendModel:
      type: object
      properties:
        uri:
          type: string
        friendsName:
          type: string
        friendsEmailAddress:
          type: string
        yourName:
          type: string
        yourEmailAddress:
          type: string
        yourMessage:
          type: string
        productId:
          type: string
        productImage:
          type: string
        productShortDescription:
          type: string
        altText:
          type: string
        productUrl:
          type: string
        properties:
          type: object
          additionalProperties:
            type: string
  securitySchemes:
    access_token:
      type: apiKey
      description: Token used to access storefront API.
      name: access_token
      in: query
