openapi: 3.2.0
info:
  version: admin-v1
  title: Admin API V1 Vmi Bins API
servers:
- url: https://dogfood.commerce.insitesandbox.com
security: []
tags:
- name: Vmi Bins
paths:
  /api/v1/admin/VmiBins:
    get:
      tags:
      - Vmi Bins
      summary: Returns the EntitySet VmiBins
      operationId: VmiBins_Get
      parameters:
      - name: $expand
        in: query
        description: Expands related entities inline.
        required: false
        schema:
          type: string
      - name: $filter
        in: query
        description: Filters the results, based on a Boolean condition.
        required: false
        schema:
          type: string
      - name: $select
        in: query
        description: Selects which properties to include in the response.
        required: false
        schema:
          type: string
      - name: $apply
        in: query
        description: Aggregates the results according to one or more transformations.
        required: false
        schema:
          type: string
      - name: $orderby
        in: query
        description: Sorts the results.
        required: false
        schema:
          type: string
      - name: $top
        in: query
        description: Returns only the first n results.
        required: false
        schema:
          type: integer
          format: int32
      - name: $skip
        in: query
        description: Skips the first n results.
        required: false
        schema:
          type: integer
          format: int32
      - name: $count
        in: query
        description: Includes a count of the matching results in the response.
        required: false
        schema:
          type: boolean
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                type: object
      deprecated: false
      security:
      - access_token: []
    post:
      tags:
      - Vmi Bins
      summary: Post a new entity to EntitySet VmiBins
      operationId: VmiBins_Post
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Insite.Data.Entities.VmiBin'
        description: The entity to post
        required: true
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                type: object
      deprecated: false
      security:
      - access_token: []
  /api/v1/admin/VmiBins({id}):
    get:
      tags:
      - Vmi Bins
      summary: Returns the entity with the key from VmiBins
      operationId: VmiBins_GetById
      parameters:
      - name: id
        in: path
        description: 'key: id'
        required: true
        schema:
          type: string
          format: uuid
      - name: $expand
        in: query
        description: Expands related entities inline.
        required: false
        schema:
          type: string
      - name: $select
        in: query
        description: Selects which properties to include in the response.
        required: false
        schema:
          type: string
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                type: object
      deprecated: false
      security:
      - access_token: []
    put:
      tags:
      - Vmi Bins
      summary: Replace entity in EntitySet VmiBins
      operationId: VmiBins_PutById
      parameters:
      - name: id
        in: path
        description: 'key: id'
        required: true
        schema:
          type: string
          format: uuid
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Insite.Data.Entities.VmiBin'
        description: The entity to put
        required: true
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                type: object
      deprecated: false
      security:
      - access_token: []
    delete:
      tags:
      - Vmi Bins
      summary: Delete entity in EntitySet VmiBins
      operationId: VmiBins_DeleteById
      parameters:
      - name: id
        in: path
        description: 'key: id'
        required: true
        schema:
          type: string
          format: uuid
      - name: If-Match
        in: header
        description: If-Match header
        required: false
        schema:
          type: string
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                type: object
      deprecated: false
      security:
      - access_token: []
    patch:
      tags:
      - Vmi Bins
      summary: Update entity in EntitySet VmiBins
      operationId: VmiBins_PatchById
      parameters:
      - name: id
        in: path
        description: 'key: id'
        required: true
        schema:
          type: string
          format: uuid
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Insite.Data.Entities.VmiBin'
        description: The entity to patch
        required: true
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                type: object
      deprecated: false
      security:
      - access_token: []
  /api/v1/admin/VmiBins/Default.Default():
    get:
      tags:
      - Vmi Bins
      summary: Call operation  Default
      operationId: VmiBins_Default
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                type: object
      deprecated: false
      security:
      - access_token: []
  /api/v1/admin/VmiBins/Default.archive:
    post:
      tags:
      - Vmi Bins
      summary: Call operation  archive
      operationId: VmiBins_Archive
      parameters:
      - name: ids
        in: query
        required: true
        explode: true
        schema:
          type: array
          items:
            type: string
            format: uuid
      requestBody:
        $ref: '#/components/requestBodies/Affiliates_ArchiveParameters'
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                type: object
      deprecated: false
      security:
      - access_token: []
  /api/v1/admin/vmibins/archive:
    delete:
      tags:
      - Vmi Bins
      operationId: VmiBins_ArchiveRoute
      parameters:
      - name: ids
        in: query
        required: true
        explode: true
        schema:
          type: array
          items:
            type: string
            format: uuid
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                type: object
      deprecated: false
      security:
      - access_token: []
  /api/v1/admin/vmibins/delete:
    delete:
      tags:
      - Vmi Bins
      operationId: VmiBins_DeleteRoute
      parameters:
      - name: ids
        in: query
        required: true
        explode: true
        schema:
          type: array
          items:
            type: string
            format: uuid
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                type: object
      deprecated: false
      security:
      - access_token: []
  /api/v1/admin/vmibins({key})/customproperties({custompropertyKey}):
    get:
      tags:
      - Vmi Bins
      operationId: VmiBins_GetCustomPropertyByKeyAndCustompropertykey
      parameters:
      - name: key
        in: path
        required: true
        schema:
          type: string
          format: uuid
      - name: custompropertyKey
        in: path
        required: true
        schema:
          type: string
          format: uuid
      - name: $expand
        in: query
        description: Expands related entities inline.
        required: false
        schema:
          type: string
      - name: $select
        in: query
        description: Selects which properties to include in the response.
        required: false
        schema:
          type: string
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                type: object
      deprecated: false
      security:
      - access_token: []
  /api/v1/admin/vmibins({key})/vmicounts({vmicountKey}):
    get:
      tags:
      - Vmi Bins
      operationId: VmiBins_GetVmiCountByKeyAndVmicountkey
      parameters:
      - name: key
        in: path
        required: true
        schema:
          type: string
          format: uuid
      - name: vmicountKey
        in: path
        required: true
        schema:
          type: string
          format: uuid
      - name: $expand
        in: query
        description: Expands related entities inline.
        required: false
        schema:
          type: string
      - name: $select
        in: query
        description: Selects which properties to include in the response.
        required: false
        schema:
          type: string
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                type: object
      deprecated: false
      security:
      - access_token: []
  /api/v1/admin/vmibins({key})/vminotes({vminoteKey}):
    get:
      tags:
      - Vmi Bins
      operationId: VmiBins_GetVmiNoteByKeyAndVminotekey
      parameters:
      - name: key
        in: path
        required: true
        schema:
          type: string
          format: uuid
      - name: vminoteKey
        in: path
        required: true
        schema:
          type: string
          format: uuid
      - name: $expand
        in: query
        description: Expands related entities inline.
        required: false
        schema:
          type: string
      - name: $select
        in: query
        description: Selects which properties to include in the response.
        required: false
        schema:
          type: string
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                type: object
      deprecated: false
      security:
      - access_token: []
components:
  schemas:
    Insite.Data.Entities.VmiBin:
      required:
      - binNumber
      - lastCountUserName
      - previousCountUserName
      - unitOfMeasure
      type: object
      properties:
        id:
          format: uuid
          type: string
          example: 00000000-0000-0000-0000-000000000000
        vmiLocationId:
          format: uuid
          type: string
          example: 00000000-0000-0000-0000-000000000000
        binNumber:
          maxLength: 25
          minLength: 0
          type: string
        productId:
          format: uuid
          type: string
          example: 00000000-0000-0000-0000-000000000000
        minimumQty:
          format: decimal
          type: number
        maximumQty:
          format: decimal
          type: number
        lastCountDate:
          format: date-time
          type: string
        lastCountQty:
          format: decimal
          type: number
        lastCountUserName:
          maxLength: 100
          minLength: 0
          type: string
        previousCountDate:
          format: date-time
          type: string
        previousCountQty:
          format: decimal
          type: number
        previousCountUserName:
          maxLength: 100
          minLength: 0
          type: string
        lastOrderDate:
          format: date-time
          type: string
        lastOrderLineId:
          format: uuid
          type: string
          example: 00000000-0000-0000-0000-000000000000
        isActive:
          type: boolean
        unitOfMeasure:
          maxLength: 50
          minLength: 0
          type: string
        createdOn:
          format: date-time
          type: string
        createdBy:
          type: string
        modifiedOn:
          format: date-time
          type: string
        modifiedBy:
          type: string
  requestBodies:
    Affiliates_ArchiveParameters:
      content:
        application/json:
          schema:
            type: object
            properties: {}
      description: archive action parameters
  securitySchemes:
    access_token:
      type: apiKey
      description: Token used to access storefront API.
      name: access_token
      in: query
