openapi: 3.2.0
info:
  version: storefront-v1
  title: Storefront API V1 Paymentauthentication API
servers:
- url: https://dogfood.commerce.insitesandbox.com
security: []
tags:
- name: Paymentauthentication
paths:
  /api/v1/paymentauthentication:
    post:
      tags:
      - Paymentauthentication
      operationId: PaymentAuthenticationV1_Post
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Insite.Payments.WebApi.V1.ApiModels.PaymentAuthenticationParameter'
          text/json:
            schema:
              $ref: '#/components/schemas/Insite.Payments.WebApi.V1.ApiModels.PaymentAuthenticationParameter'
          application/xml:
            schema:
              $ref: '#/components/schemas/Insite.Payments.WebApi.V1.ApiModels.PaymentAuthenticationParameter'
          text/xml:
            schema:
              $ref: '#/components/schemas/Insite.Payments.WebApi.V1.ApiModels.PaymentAuthenticationParameter'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Insite.Payments.WebApi.V1.ApiModels.PaymentAuthenticationParameter'
          text/html:
            schema:
              $ref: '#/components/schemas/Insite.Payments.WebApi.V1.ApiModels.PaymentAuthenticationParameter'
        required: true
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Insite.Payments.WebApi.V1.ApiModels.PaymentAuthenticationModel'
            text/json:
              schema:
                $ref: '#/components/schemas/Insite.Payments.WebApi.V1.ApiModels.PaymentAuthenticationModel'
            text/html:
              schema:
                $ref: '#/components/schemas/Insite.Payments.WebApi.V1.ApiModels.PaymentAuthenticationModel'
      security:
      - access_token: []
  /api/v1/paymentauthentication/threedsnotify:
    post:
      tags:
      - Paymentauthentication
      operationId: PaymentAuthenticationV1_Post2
      requestBody:
        $ref: '#/components/requestBodies/PaymentAuthenticationV1_Post2Parameter'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
            text/json:
              schema:
                type: object
            application/xml:
              schema:
                type: object
            text/xml:
              schema:
                type: object
            text/html:
              schema:
                type: object
  /api/v1/paymentauthentication/adyenwebhook:
    post:
      tags:
      - Paymentauthentication
      operationId: PaymentAuthenticationV1_AdyenWebhook
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Insite.Payments.WebApi.V1.ApiModels.AdyenWebhook.WebhookModel'
          text/json:
            schema:
              $ref: '#/components/schemas/Insite.Payments.WebApi.V1.ApiModels.AdyenWebhook.WebhookModel'
          application/xml:
            schema:
              $ref: '#/components/schemas/Insite.Payments.WebApi.V1.ApiModels.AdyenWebhook.WebhookModel'
          text/xml:
            schema:
              $ref: '#/components/schemas/Insite.Payments.WebApi.V1.ApiModels.AdyenWebhook.WebhookModel'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Insite.Payments.WebApi.V1.ApiModels.AdyenWebhook.WebhookModel'
          text/html:
            schema:
              $ref: '#/components/schemas/Insite.Payments.WebApi.V1.ApiModels.AdyenWebhook.WebhookModel'
        required: true
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
            text/json:
              schema:
                type: object
            application/xml:
              schema:
                type: object
            text/xml:
              schema:
                type: object
            text/html:
              schema:
                type: object
  /api/v1/paymentauthentication/adyenpaymentdetails:
    post:
      tags:
      - Paymentauthentication
      operationId: PaymentAuthenticationV1_AdyenPaymentDetails
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Insite.Payments.WebApi.V1.ApiModels.AdyenPaymentDetails.PaymentDetailsRequest'
          text/json:
            schema:
              $ref: '#/components/schemas/Insite.Payments.WebApi.V1.ApiModels.AdyenPaymentDetails.PaymentDetailsRequest'
          application/xml:
            schema:
              $ref: '#/components/schemas/Insite.Payments.WebApi.V1.ApiModels.AdyenPaymentDetails.PaymentDetailsRequest'
          text/xml:
            schema:
              $ref: '#/components/schemas/Insite.Payments.WebApi.V1.ApiModels.AdyenPaymentDetails.PaymentDetailsRequest'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Insite.Payments.WebApi.V1.ApiModels.AdyenPaymentDetails.PaymentDetailsRequest'
          text/html:
            schema:
              $ref: '#/components/schemas/Insite.Payments.WebApi.V1.ApiModels.AdyenPaymentDetails.PaymentDetailsRequest'
        required: true
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
            text/json:
              schema:
                type: object
            application/xml:
              schema:
                type: object
            text/xml:
              schema:
                type: object
            text/html:
              schema:
                type: object
      security:
      - access_token: []
  /api/v1/paymentauthentication/adyenpayment:
    post:
      tags:
      - Paymentauthentication
      operationId: PaymentAuthenticationV1_AdyenPayment
      requestBody:
        $ref: '#/components/requestBodies/PaymentAuthenticationV1_Post2Parameter'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
            text/json:
              schema:
                type: object
            application/xml:
              schema:
                type: object
            text/xml:
              schema:
                type: object
            text/html:
              schema:
                type: object
      security:
      - access_token: []
  /api/v1/paymentauthentication/adyenrefund:
    post:
      tags:
      - Paymentauthentication
      operationId: PaymentAuthenticationV1_Refund
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Insite.Payments.WebApi.V1.ApiModels.AdyenRefundParameter'
          text/json:
            schema:
              $ref: '#/components/schemas/Insite.Payments.WebApi.V1.ApiModels.AdyenRefundParameter'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Insite.Payments.WebApi.V1.ApiModels.AdyenRefundParameter'
          text/html:
            schema:
              $ref: '#/components/schemas/Insite.Payments.WebApi.V1.ApiModels.AdyenRefundParameter'
        required: true
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
            text/json:
              schema:
                type: object
            application/xml:
              schema:
                type: object
            text/xml:
              schema:
                type: object
            text/html:
              schema:
                type: object
      security:
      - access_token: []
  /api/v1/paymentauthentication/threedschallengeresponse:
    post:
      tags:
      - Paymentauthentication
      operationId: PaymentAuthenticationV1_PostAsync
      requestBody:
        $ref: '#/components/requestBodies/PaymentAuthenticationV1_Post2Parameter'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Insite.Payments.WebApi.V1.ApiModels.ThreeDsChallengeResult'
            text/json:
              schema:
                $ref: '#/components/schemas/Insite.Payments.WebApi.V1.ApiModels.ThreeDsChallengeResult'
            application/xml:
              schema:
                $ref: '#/components/schemas/Insite.Payments.WebApi.V1.ApiModels.ThreeDsChallengeResult'
            text/xml:
              schema:
                $ref: '#/components/schemas/Insite.Payments.WebApi.V1.ApiModels.ThreeDsChallengeResult'
            text/html:
              schema:
                $ref: '#/components/schemas/Insite.Payments.WebApi.V1.ApiModels.ThreeDsChallengeResult'
  /api/v1/paymentauthentication/threedscallback:
    post:
      tags:
      - Paymentauthentication
      operationId: PaymentAuthenticationV1_PostAsync2
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
            text/json:
              schema:
                type: object
            application/xml:
              schema:
                type: object
            text/xml:
              schema:
                type: object
            text/html:
              schema:
                type: object
  /api/v1/paymentauthentication/bnplcallback:
    post:
      tags:
      - Paymentauthentication
      operationId: PaymentAuthenticationV1_BnplCallbackAsync
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
            text/json:
              schema:
                type: object
            application/xml:
              schema:
                type: object
            text/xml:
              schema:
                type: object
            text/html:
              schema:
                type: object
components:
  schemas:
    Insite.Payments.WebApi.V1.ApiModels.AdyenWebhook.NotificationRequestItemModel:
      type: object
      properties:
        additionalData:
          $ref: '#/components/schemas/Insite.Payments.WebApi.V1.ApiModels.AdyenWebhook.AdditionalDataModel'
        merchantAccountCode:
          type: string
        merchantReference:
          type: string
        originalReference:
          type: string
        paymentMethod:
          type: string
        operations:
          type: array
          items:
            type: string
        pspReference:
          type: string
        amount:
          $ref: '#/components/schemas/Insite.Payments.WebApi.V1.ApiModels.AdyenWebhook.AmountModel'
        eventCode:
          type: string
        eventDate:
          type: string
        reason:
          type: string
        success:
          type: boolean
    Insite.Payments.WebApi.V1.ApiModels.ThreeDsChallengeResult:
      type: object
      properties:
        messageId:
          type: string
        threeDSServerTransID:
          format: uuid
          type: string
          example: 00000000-0000-0000-0000-000000000000
        valid:
          type: boolean
        rReq:
          $ref: '#/components/schemas/Insite.Payments.WebApi.V1.ApiModels.ThreeDSChallengeRreq'
    Insite.Payments.WebApi.V1.ApiModels.AdyenWebhook.AdditionalDataModel:
      type: object
      properties:
        threeDs2CardEnrolled:
          type: string
        checkoutSessionId:
          type: string
        hmacSignature:
          type: string
        cardSummary:
          type: string
        expiryDate:
          type: string
        authCode:
          type: string
    Insite.Payments.WebApi.V1.ApiModels.AdyenPaymentDetails.PaymentDetailsRequest:
      type: object
      properties:
        details:
          $ref: '#/components/schemas/Insite.Payments.WebApi.V1.ApiModels.AdyenPaymentDetails.Details'
    Insite.Payments.WebApi.V1.ApiModels.AdyenPaymentDetails.Details:
      type: object
      properties:
        redirectResult:
          type: string
    Insite.Core.Plugins.PaymentGateway.Dtos.ThreeDsDto:
      type: object
      properties:
        dsTransId:
          format: uuid
          type: string
          example: 00000000-0000-0000-0000-000000000000
        iframeIsChallenge:
          type: boolean
        iframeIsHidden:
          type: boolean
        rejected:
          type: boolean
        acsEci:
          type: string
        authenticationToken:
          type: string
        authenticationVersion:
          type: string
        iframe:
          type: string
        messageId:
          type: string
        transStatus:
          type: string
    Insite.Payments.WebApi.V1.ApiModels.AdyenWebhook.AmountModel:
      type: object
      properties:
        currency:
          type: string
        value:
          format: int32
          type: integer
    Insite.Payments.WebApi.V1.ApiModels.ThreeDSChallengeRreq:
      type: object
      properties:
        messageType:
          type: string
        messageVersion:
          type: string
        threeDSServerTransID:
          format: uuid
          type: string
          example: 00000000-0000-0000-0000-000000000000
        dsTransID:
          format: uuid
          type: string
          example: 00000000-0000-0000-0000-000000000000
        acsTransID:
          format: uuid
          type: string
          example: 00000000-0000-0000-0000-000000000000
        authenticationType:
          type: string
        authenticationValue:
          type: string
        eci:
          type: string
        interactionCounter:
          type: string
        messageCategory:
          type: string
        transStatus:
          type: string
    Insite.Payments.WebApi.V1.ApiModels.PaymentAuthenticationModel:
      type: object
      properties:
        transactionId:
          type: string
        webOrderNumber:
          type: string
        threeDs:
          $ref: '#/components/schemas/Insite.Core.Plugins.PaymentGateway.Dtos.ThreeDsDto'
        sessionData:
          type: string
        action:
          type: string
        region:
          type: string
    Insite.Payments.WebApi.V1.ApiModels.AdyenWebhook.WebhookModel:
      type: object
      properties:
        notificationItems:
          type: array
          items:
            $ref: '#/components/schemas/Insite.Payments.WebApi.V1.ApiModels.AdyenWebhook.NotificationItemModel'
        live:
          type: boolean
    Insite.Payments.WebApi.V1.ApiModels.PaymentAuthenticationParameter:
      type: object
      properties:
        currency:
          type: string
        transactionId:
          type: string
        cardNumber:
          type: string
        expirationMonth:
          format: int32
          type: integer
        expirationYear:
          format: int32
          type: integer
        orderAmount:
          type: string
        operation:
          type: string
        returnUrl:
          type: string
        cartId:
          format: uuid
          type: string
          example: 00000000-0000-0000-0000-000000000000
        isPaymentProfile:
          type: boolean
        webOrderNumber:
          type: string
        resume3Ds:
          type: boolean
    Insite.Payments.WebApi.V1.ApiModels.AdyenWebhook.NotificationItemModel:
      type: object
      properties:
        notificationRequestItem:
          $ref: '#/components/schemas/Insite.Payments.WebApi.V1.ApiModels.AdyenWebhook.NotificationRequestItemModel'
    Insite.Payments.WebApi.V1.ApiModels.AdyenRefundParameter:
      type: object
      properties:
        pspReference:
          type: string
        orderNumber:
          type: string
        amount:
          $ref: '#/components/schemas/Insite.Payments.WebApi.V1.ApiModels.AdyenWebhook.AmountModel'
  requestBodies:
    PaymentAuthenticationV1_Post2Parameter:
      content:
        application/json:
          schema:
            type: object
        text/json:
          schema:
            type: object
        application/x-www-form-urlencoded:
          schema:
            type: object
        text/html:
          schema:
            type: object
      required: true
  securitySchemes:
    access_token:
      type: apiKey
      description: Token used to access storefront API.
      name: access_token
      in: query
