openapi: 3.2.0
info:
  version: admin-v1
  title: Admin API V1 Content Item Fields API
servers:
- url: https://dogfood.commerce.insitesandbox.com
security: []
tags:
- name: Content Item Fields
paths:
  /api/v1/admin/ContentItemFields:
    get:
      tags:
      - Content Item Fields
      summary: Returns the EntitySet ContentItemFields
      operationId: ContentItemFields_Get
      parameters:
      - name: $expand
        in: query
        description: Expands related entities inline.
        required: false
        schema:
          type: string
      - name: $filter
        in: query
        description: Filters the results, based on a Boolean condition.
        required: false
        schema:
          type: string
      - name: $select
        in: query
        description: Selects which properties to include in the response.
        required: false
        schema:
          type: string
      - name: $apply
        in: query
        description: Aggregates the results according to one or more transformations.
        required: false
        schema:
          type: string
      - name: $orderby
        in: query
        description: Sorts the results.
        required: false
        schema:
          type: string
      - name: $top
        in: query
        description: Returns only the first n results.
        required: false
        schema:
          type: integer
          format: int32
      - name: $skip
        in: query
        description: Skips the first n results.
        required: false
        schema:
          type: integer
          format: int32
      - name: $count
        in: query
        description: Includes a count of the matching results in the response.
        required: false
        schema:
          type: boolean
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                type: object
      deprecated: false
      security:
      - access_token: []
    post:
      tags:
      - Content Item Fields
      summary: Post a new entity to EntitySet ContentItemFields
      operationId: ContentItemFields_Post
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Insite.Data.Entities.ContentItemField'
        description: The entity to post
        required: true
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                type: object
      deprecated: false
      security:
      - access_token: []
  /api/v1/admin/ContentItemFields({id}):
    get:
      tags:
      - Content Item Fields
      summary: Returns the entity with the key from ContentItemFields
      operationId: ContentItemFields_GetById
      parameters:
      - name: id
        in: path
        description: 'key: id'
        required: true
        schema:
          type: string
          format: uuid
      - name: $expand
        in: query
        description: Expands related entities inline.
        required: false
        schema:
          type: string
      - name: $select
        in: query
        description: Selects which properties to include in the response.
        required: false
        schema:
          type: string
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                type: object
      deprecated: false
      security:
      - access_token: []
    put:
      tags:
      - Content Item Fields
      summary: Replace entity in EntitySet ContentItemFields
      operationId: ContentItemFields_PutById
      parameters:
      - name: id
        in: path
        description: 'key: id'
        required: true
        schema:
          type: string
          format: uuid
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Insite.Data.Entities.ContentItemField'
        description: The entity to put
        required: true
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                type: object
      deprecated: false
      security:
      - access_token: []
    delete:
      tags:
      - Content Item Fields
      summary: Delete entity in EntitySet ContentItemFields
      operationId: ContentItemFields_DeleteById
      parameters:
      - name: id
        in: path
        description: 'key: id'
        required: true
        schema:
          type: string
          format: uuid
      - name: If-Match
        in: header
        description: If-Match header
        required: false
        schema:
          type: string
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                type: object
      deprecated: false
      security:
      - access_token: []
    patch:
      tags:
      - Content Item Fields
      summary: Update entity in EntitySet ContentItemFields
      operationId: ContentItemFields_PatchById
      parameters:
      - name: id
        in: path
        description: 'key: id'
        required: true
        schema:
          type: string
          format: uuid
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Insite.Data.Entities.ContentItemField'
        description: The entity to patch
        required: true
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                type: object
      deprecated: false
      security:
      - access_token: []
  /api/v1/admin/ContentItemFields/Default.Default():
    get:
      tags:
      - Content Item Fields
      summary: Call operation  Default
      operationId: ContentItemFields_Default
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                type: object
      deprecated: false
      security:
      - access_token: []
  /api/v1/admin/contentitemfields/delete:
    delete:
      tags:
      - Content Item Fields
      operationId: ContentItemFields_DeleteRoute
      parameters:
      - name: ids
        in: query
        required: true
        explode: true
        schema:
          type: array
          items:
            type: string
            format: uuid
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                type: object
      deprecated: false
      security:
      - access_token: []
  /api/v1/admin/contentitemfields({key})/customproperties({custompropertyKey}):
    get:
      tags:
      - Content Item Fields
      operationId: ContentItemFields_GetCustomPropertyByKeyAndCustompropertykey
      parameters:
      - name: key
        in: path
        required: true
        schema:
          type: string
          format: uuid
      - name: custompropertyKey
        in: path
        required: true
        schema:
          type: string
          format: uuid
      - name: $expand
        in: query
        description: Expands related entities inline.
        required: false
        schema:
          type: string
      - name: $select
        in: query
        description: Selects which properties to include in the response.
        required: false
        schema:
          type: string
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                type: object
      deprecated: false
      security:
      - access_token: []
components:
  schemas:
    Insite.Data.Entities.ContentItemField:
      required:
      - deviceType
      - fieldType
      - fieldName
      type: object
      properties:
        id:
          format: uuid
          type: string
          example: 00000000-0000-0000-0000-000000000000
        contentKey:
          format: int32
          type: integer
        languageId:
          format: uuid
          type: string
          example: 00000000-0000-0000-0000-000000000000
        personaId:
          format: uuid
          type: string
          example: 00000000-0000-0000-0000-000000000000
        deviceType:
          maxLength: 50
          minLength: 0
          type: string
        fieldType:
          maxLength: 50
          minLength: 0
          type: string
        fieldName:
          maxLength: 100
          minLength: 0
          type: string
        isSharedField:
          type: boolean
        dateTimeValue:
          format: date-time
          type: string
        decimalValue:
          format: double
          type: number
        intValue:
          format: int32
          type: integer
        stringValue:
          type: string
        booleanValue:
          type: boolean
        objectValue:
          format: byte
          type: string
        publishOn:
          format: date-time
          type: string
        approvedOn:
          format: date-time
          type: string
        submittedForApprovalOn:
          format: date-time
          type: string
        createdById:
          format: uuid
          type: string
          example: 00000000-0000-0000-0000-000000000000
        approvedById:
          format: uuid
          type: string
          example: 00000000-0000-0000-0000-000000000000
        isRetracted:
          type: boolean
        isRollback:
          type: boolean
        createdOn:
          format: date-time
          type: string
        createdBy:
          type: string
        modifiedOn:
          format: date-time
          type: string
        modifiedBy:
          type: string
  securitySchemes:
    access_token:
      type: apiKey
      description: Token used to access storefront API.
      name: access_token
      in: query
