openapi: 3.2.0
info:
  version: admin-v1
  title: Admin API V1 Entity Definitions API
servers:
- url: https://dogfood.commerce.insitesandbox.com
security: []
tags:
- name: Entity Definitions
paths:
  /api/v1/admin/EntityDefinitions:
    get:
      tags:
      - Entity Definitions
      summary: Returns the EntitySet EntityDefinitions
      operationId: EntityDefinitions_Get
      parameters:
      - name: $expand
        in: query
        description: Expands related entities inline.
        required: false
        schema:
          type: string
      - name: $filter
        in: query
        description: Filters the results, based on a Boolean condition.
        required: false
        schema:
          type: string
      - name: $select
        in: query
        description: Selects which properties to include in the response.
        required: false
        schema:
          type: string
      - name: $apply
        in: query
        description: Aggregates the results according to one or more transformations.
        required: false
        schema:
          type: string
      - name: $orderby
        in: query
        description: Sorts the results.
        required: false
        schema:
          type: string
      - name: $top
        in: query
        description: Returns only the first n results.
        required: false
        schema:
          type: integer
          format: int32
      - name: $skip
        in: query
        description: Skips the first n results.
        required: false
        schema:
          type: integer
          format: int32
      - name: $count
        in: query
        description: Includes a count of the matching results in the response.
        required: false
        schema:
          type: boolean
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                type: object
      deprecated: false
  /api/v1/admin/EntityDefinitions('{name}'):
    get:
      tags:
      - Entity Definitions
      summary: Returns the entity with the key from EntityDefinitions
      operationId: EntityDefinitions_GetByName
      parameters:
      - name: name
        in: path
        description: 'key: name'
        required: true
        schema:
          type: string
      - name: $expand
        in: query
        description: Expands related entities inline.
        required: false
        schema:
          type: string
      - name: $select
        in: query
        description: Selects which properties to include in the response.
        required: false
        schema:
          type: string
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                type: object
      deprecated: false
  /api/v1/admin/EntityDefinitions/Default.PropertyValidations(entityName='{entityName}'):
    get:
      tags:
      - Entity Definitions
      summary: Call operation  PropertyValidations
      operationId: EntityDefinitions_GetPropertyValidationsByEntityname_1
      parameters:
      - name: entityName
        in: path
        description: 'parameter: entityName'
        required: true
        schema:
          type: string
      - name: $expand
        in: query
        description: Expands related entities inline.
        required: false
        schema:
          type: string
      - name: $select
        in: query
        description: Selects which properties to include in the response.
        required: false
        schema:
          type: string
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                type: object
      deprecated: false
  /api/v1/admin/EntityDefinitions/Default.DisplayNameFormats():
    get:
      tags:
      - Entity Definitions
      summary: Call operation  DisplayNameFormats
      operationId: EntityDefinitions_GetDisplayNameFormats_1
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                type: object
      deprecated: false
  /api/v1/admin/entitydefinitions/PropertyValidations(entityName='{entityName}'):
    get:
      tags:
      - Entity Definitions
      operationId: EntityDefinitions_GetPropertyValidationsByEntityname_2
      parameters:
      - name: entityName
        in: path
        required: true
        schema:
          type: string
      - name: $expand
        in: query
        description: Expands related entities inline.
        required: false
        schema:
          type: string
      - name: $select
        in: query
        description: Selects which properties to include in the response.
        required: false
        schema:
          type: string
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                type: object
      deprecated: false
  /api/v1/admin/entitydefinitions/displayNameFormats:
    get:
      tags:
      - Entity Definitions
      operationId: EntityDefinitions_GetDisplayNameFormats_2
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                type: object
      deprecated: false
components:
  securitySchemes:
    access_token:
      type: apiKey
      description: Token used to access storefront API.
      name: access_token
      in: query
