openapi: 3.2.0
info:
  title: Optimizely Agent OAUTH API
  description: Optimizely Agent is a stand-alone, open-source microservice that provides major benefits over using Optimizely SDKs in certain use cases. Its REST API offers consolidated and simplified endpoints for accessing all the functionality of Optimizely Feature Experimentation SDKs. Use this API the control experiments (such as a feature tests). For more info, see https://docs.developers.optimizely.com/experimentation/v4.0.0-full-stack/docs/optimizely-agent
  termsOfService: https://www.optimizely.com/legal/terms/
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
  version: 0.12.0
security:
- SdkKeyAuth: []
- TokenAuth: []
tags:
- name: Oauth
paths:
  /oauth/token:
    post:
      summary: Get JWT token to authenticate all requests.
      description: Generates valid JWT token for grant_type, client_id, and client_secret, using the values you pass in the request body.  Configure expiration time and SDK keys (to which the token grants access) in Optimizely config.
      operationId: getToken
      requestBody:
        description: ''
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TokenContext'
        required: true
      responses:
        '200':
          description: Generates a valid token
          content:
            application/json: {}
        '401':
          description: Unable to match credentials
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TokenError'
      deprecated: false
      tags:
      - Oauth
components:
  schemas:
    TokenError:
      title: TokenError
      type: object
      properties:
        error:
          type: string
        error_description:
          type: string
    TokenContext:
      title: TokenContext
      type: object
      properties:
        grant_type:
          type: string
        client_id:
          type: string
        client_secret:
          type: string
  securitySchemes:
    SdkKeyAuth:
      type: apiKey
      name: X-Optimizely-SDK-Key
      in: header
    TokenAuth:
      type: http
      scheme: bearer
      bearerFormat: jwt
x-readme:
  explorer-enabled: true
  proxy-enabled: true
