openapi: 3.2.0
info:
  version: storefront-v1
  title: Storefront API V1 Tokenexconfig API
servers:
- url: https://dogfood.commerce.insitesandbox.com
security: []
tags:
- name: Tokenexconfig
paths:
  /api/v1/tokenexconfig:
    get:
      tags:
      - Tokenexconfig
      operationId: TokenExConfigV1_Get
      parameters:
      - name: token
        in: query
        required: false
        schema:
          type: string
      - name: isECheck
        in: query
        required: false
        schema:
          type: boolean
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
            text/json:
              schema:
                type: object
            application/xml:
              schema:
                type: object
            text/xml:
              schema:
                type: object
            text/html:
              schema:
                type: object
      security:
      - access_token: []
components:
  securitySchemes:
    access_token:
      type: apiKey
      description: Token used to access storefront API.
      name: access_token
      in: query
