openapi: 3.2.0
info:
  version: admin-v1
  title: Admin API V1 Spreedly Config API
servers:
- url: https://dogfood.commerce.insitesandbox.com
security: []
tags:
- name: Spreedly Config
paths:
  /api/v1/admin/spreedlyconfig:
    get:
      tags:
      - Spreedly Config
      operationId: SpreedlyConfig_Get
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
            text/json:
              schema:
                type: object
            application/xml:
              schema:
                type: object
            text/xml:
              schema:
                type: object
            text/html:
              schema:
                type: object
      security:
      - access_token: []
components:
  securitySchemes:
    access_token:
      type: apiKey
      description: Token used to access storefront API.
      name: access_token
      in: query
