openapi: 3.2.0
info:
  version: storefront-v1
  title: Storefront API V1 Applepay API
servers:
- url: https://dogfood.commerce.insitesandbox.com
security: []
tags:
- name: Applepay
paths:
  /api/v1/applepay/session:
    post:
      tags:
      - Applepay
      operationId: ApplePaySession_ValidateSessionAsync
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Insite.Websites.WebApi.V1.ApiModels.ApplePaySessionRequestModel'
          text/json:
            schema:
              $ref: '#/components/schemas/Insite.Websites.WebApi.V1.ApiModels.ApplePaySessionRequestModel'
          application/xml:
            schema:
              $ref: '#/components/schemas/Insite.Websites.WebApi.V1.ApiModels.ApplePaySessionRequestModel'
          text/xml:
            schema:
              $ref: '#/components/schemas/Insite.Websites.WebApi.V1.ApiModels.ApplePaySessionRequestModel'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Insite.Websites.WebApi.V1.ApiModels.ApplePaySessionRequestModel'
          text/html:
            schema:
              $ref: '#/components/schemas/Insite.Websites.WebApi.V1.ApiModels.ApplePaySessionRequestModel'
        required: true
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
            text/json:
              schema:
                type: object
            application/xml:
              schema:
                type: object
            text/xml:
              schema:
                type: object
            text/html:
              schema:
                type: object
      security:
      - access_token: []
  /api/v1/applepay/config:
    get:
      tags:
      - Applepay
      operationId: ApplePayV1_Get
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
            text/json:
              schema:
                type: object
            application/xml:
              schema:
                type: object
            text/xml:
              schema:
                type: object
            text/html:
              schema:
                type: object
      security:
      - access_token: []
components:
  schemas:
    Insite.Websites.WebApi.V1.ApiModels.ApplePaySessionRequestModel:
      type: object
      properties:
        validationUrl:
          type: string
        domainName:
          type: string
  securitySchemes:
    access_token:
      type: apiKey
      description: Token used to access storefront API.
      name: access_token
      in: query
