openapi: 3.2.0
info:
  version: storefront-v1
  title: Storefront API V1 Budgets API
servers:
- url: https://dogfood.commerce.insitesandbox.com
security: []
tags:
- name: Budgets
paths:
  /api/v1/budgets:
    get:
      tags:
      - Budgets
      operationId: BudgetsV1_GetCollectionAsync
      parameters:
      - name: parameter.shipToId
        in: query
        required: false
        schema:
          type: string
          format: uuid
      - name: parameter.userProfileId
        in: query
        required: false
        schema:
          type: string
          format: uuid
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Insite.Budget.WebApi.V1.ApiModels.BudgetCollectionModel'
            text/json:
              schema:
                $ref: '#/components/schemas/Insite.Budget.WebApi.V1.ApiModels.BudgetCollectionModel'
            application/xml:
              schema:
                $ref: '#/components/schemas/Insite.Budget.WebApi.V1.ApiModels.BudgetCollectionModel'
            text/xml:
              schema:
                $ref: '#/components/schemas/Insite.Budget.WebApi.V1.ApiModels.BudgetCollectionModel'
            text/html:
              schema:
                $ref: '#/components/schemas/Insite.Budget.WebApi.V1.ApiModels.BudgetCollectionModel'
      security:
      - access_token: []
  /api/v1/budgets/{fiscalYear}:
    get:
      tags:
      - Budgets
      operationId: BudgetsV1_GetAsync
      parameters:
      - name: fiscalYear
        in: path
        required: true
        schema:
          type: integer
          format: int32
      - name: parameter.fiscalYear
        in: query
        required: false
        schema:
          type: integer
          format: int32
      - name: parameter.shipToId
        in: query
        required: false
        schema:
          type: string
          format: uuid
      - name: parameter.userProfileId
        in: query
        required: false
        schema:
          type: string
          format: uuid
      - name: parameter.fullGrid
        in: query
        required: false
        schema:
          type: boolean
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Insite.Budget.WebApi.V1.ApiModels.BudgetModel'
            text/json:
              schema:
                $ref: '#/components/schemas/Insite.Budget.WebApi.V1.ApiModels.BudgetModel'
            application/xml:
              schema:
                $ref: '#/components/schemas/Insite.Budget.WebApi.V1.ApiModels.BudgetModel'
            text/xml:
              schema:
                $ref: '#/components/schemas/Insite.Budget.WebApi.V1.ApiModels.BudgetModel'
            text/html:
              schema:
                $ref: '#/components/schemas/Insite.Budget.WebApi.V1.ApiModels.BudgetModel'
      security:
      - access_token: []
    patch:
      tags:
      - Budgets
      operationId: BudgetsV1_PatchAsync
      parameters:
      - name: fiscalYear
        in: path
        required: true
        schema:
          type: integer
          format: int32
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Insite.Budget.WebApi.V1.ApiModels.BudgetModel'
          text/json:
            schema:
              $ref: '#/components/schemas/Insite.Budget.WebApi.V1.ApiModels.BudgetModel'
          application/xml:
            schema:
              $ref: '#/components/schemas/Insite.Budget.WebApi.V1.ApiModels.BudgetModel'
          text/xml:
            schema:
              $ref: '#/components/schemas/Insite.Budget.WebApi.V1.ApiModels.BudgetModel'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Insite.Budget.WebApi.V1.ApiModels.BudgetModel'
          text/html:
            schema:
              $ref: '#/components/schemas/Insite.Budget.WebApi.V1.ApiModels.BudgetModel'
        required: true
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Insite.Budget.WebApi.V1.ApiModels.BudgetModel'
            text/json:
              schema:
                $ref: '#/components/schemas/Insite.Budget.WebApi.V1.ApiModels.BudgetModel'
            application/xml:
              schema:
                $ref: '#/components/schemas/Insite.Budget.WebApi.V1.ApiModels.BudgetModel'
            text/xml:
              schema:
                $ref: '#/components/schemas/Insite.Budget.WebApi.V1.ApiModels.BudgetModel'
            text/html:
              schema:
                $ref: '#/components/schemas/Insite.Budget.WebApi.V1.ApiModels.BudgetModel'
      security:
      - access_token: []
components:
  schemas:
    Insite.Budget.WebApi.V1.ApiModels.BudgetCollectionModel:
      type: object
      properties:
        uri:
          type: string
        budgetCollection:
          type: array
          items:
            $ref: '#/components/schemas/Insite.Budget.WebApi.V1.ApiModels.BudgetModel'
        properties:
          type: object
          additionalProperties:
            type: string
    Insite.Budget.WebApi.V1.ApiModels.BudgetLineModel:
      type: object
      properties:
        uri:
          type: string
        period:
          format: int32
          type: integer
        startDate:
          format: date-time
          type: string
        currentFiscalYearBudget:
          format: decimal
          type: number
        currentFiscalYearBudgetDisplay:
          type: string
        currentFiscalYearActual:
          format: decimal
          type: number
        currentFiscalYearActualDisplay:
          type: string
        currentFiscalYearVariance:
          format: decimal
          type: number
        currentFiscalYearVarianceDisplay:
          type: string
        lastFiscalYearBudget:
          format: decimal
          type: number
        lastFiscalYearBudgetDisplay:
          type: string
        lastFiscalYearActual:
          format: decimal
          type: number
        lastFiscalYearActualDisplay:
          type: string
        lastFiscalYearVariance:
          format: decimal
          type: number
        lastFiscalYearVarianceDisplay:
          type: string
        properties:
          type: object
          additionalProperties:
            type: string
    Insite.Budget.WebApi.V1.ApiModels.BudgetModel:
      type: object
      properties:
        uri:
          type: string
        fiscalYear:
          format: int32
          type: integer
        fiscalYearEndDate:
          format: date-time
          type: string
        budgetLineCollection:
          type: array
          items:
            $ref: '#/components/schemas/Insite.Budget.WebApi.V1.ApiModels.BudgetLineModel'
        userProfileId:
          type: string
        shipToId:
          type: string
        properties:
          type: object
          additionalProperties:
            type: string
  securitySchemes:
    access_token:
      type: apiKey
      description: Token used to access storefront API.
      name: access_token
      in: query
