openapi: 3.2.0
info:
  version: admin-v1
  title: Admin API V1 Telemetry API
servers:
- url: https://dogfood.commerce.insitesandbox.com
security: []
tags:
- name: Telemetry
paths:
  /api/v1/admin/telemetry/track-event:
    post:
      tags:
      - Telemetry
      operationId: TelemetryV1_TrackEvent
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Insite.Admin.Controllers.Api.TelemetryV1Controller.TrackEventRequest'
          text/json:
            schema:
              $ref: '#/components/schemas/Insite.Admin.Controllers.Api.TelemetryV1Controller.TrackEventRequest'
          application/xml:
            schema:
              $ref: '#/components/schemas/Insite.Admin.Controllers.Api.TelemetryV1Controller.TrackEventRequest'
          text/xml:
            schema:
              $ref: '#/components/schemas/Insite.Admin.Controllers.Api.TelemetryV1Controller.TrackEventRequest'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Insite.Admin.Controllers.Api.TelemetryV1Controller.TrackEventRequest'
          text/html:
            schema:
              $ref: '#/components/schemas/Insite.Admin.Controllers.Api.TelemetryV1Controller.TrackEventRequest'
        required: true
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
            text/json:
              schema:
                type: object
            application/xml:
              schema:
                type: object
            text/xml:
              schema:
                type: object
            text/html:
              schema:
                type: object
  /api/v1/admin/telemetry/screen-event:
    post:
      tags:
      - Telemetry
      operationId: TelemetryV1_ScreenEvent
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Insite.Admin.Controllers.Api.TelemetryV1Controller.ScreenEventRequest'
          text/json:
            schema:
              $ref: '#/components/schemas/Insite.Admin.Controllers.Api.TelemetryV1Controller.ScreenEventRequest'
          application/xml:
            schema:
              $ref: '#/components/schemas/Insite.Admin.Controllers.Api.TelemetryV1Controller.ScreenEventRequest'
          text/xml:
            schema:
              $ref: '#/components/schemas/Insite.Admin.Controllers.Api.TelemetryV1Controller.ScreenEventRequest'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Insite.Admin.Controllers.Api.TelemetryV1Controller.ScreenEventRequest'
          text/html:
            schema:
              $ref: '#/components/schemas/Insite.Admin.Controllers.Api.TelemetryV1Controller.ScreenEventRequest'
        required: true
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
            text/json:
              schema:
                type: object
            application/xml:
              schema:
                type: object
            text/xml:
              schema:
                type: object
            text/html:
              schema:
                type: object
components:
  schemas:
    Insite.Admin.Controllers.Api.TelemetryV1Controller.ScreenEventRequest:
      type: object
      properties:
        screenName:
          type: string
        properties:
          type: object
          additionalProperties:
            type: object
    Insite.Admin.Controllers.Api.TelemetryV1Controller.TrackEventRequest:
      type: object
      properties:
        eventName:
          type: string
        properties:
          type: object
          additionalProperties:
            type: object
  securitySchemes:
    access_token:
      type: apiKey
      description: Token used to access storefront API.
      name: access_token
      in: query
