openapi: 3.2.0
info:
  version: storefront-v1
  title: Storefront API V1 Punchout API
servers:
- url: https://dogfood.commerce.insitesandbox.com
security: []
tags:
- name: Punchout
paths:
  /api/v1/punchout/setuprequest:
    post:
      tags:
      - Punchout
      operationId: PunchOutV1_SetupRequestAsync
      parameters:
      - name: request
        in: query
        required: true
        schema:
          type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
            text/json:
              schema:
                type: object
            application/xml:
              schema:
                type: object
            text/xml:
              schema:
                type: object
            text/html:
              schema:
                type: object
  /api/v1/punchout/sessionrequest:
    get:
      tags:
      - Punchout
      operationId: PunchOutV1_SessionRequestAsync
      parameters:
      - name: punchoutsessionid
        in: query
        required: true
        schema:
          type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
            text/json:
              schema:
                type: object
            application/xml:
              schema:
                type: object
            text/xml:
              schema:
                type: object
            text/html:
              schema:
                type: object
  /api/v1/punchout/profiletransactionrequest:
    post:
      tags:
      - Punchout
      operationId: PunchOutV1_ProfileTransactionRequestAsync
      parameters:
      - name: request
        in: query
        required: true
        schema:
          type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
            text/json:
              schema:
                type: object
            application/xml:
              schema:
                type: object
            text/xml:
              schema:
                type: object
            text/html:
              schema:
                type: object
  /api/v1/punchout/porequisition:
    get:
      tags:
      - Punchout
      operationId: PunchOutV1_PoRequisitionAsync
      parameters:
      - name: operation
        in: query
        required: false
        schema:
          type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
            text/json:
              schema:
                type: object
            application/xml:
              schema:
                type: object
            text/xml:
              schema:
                type: object
            text/html:
              schema:
                type: object
  /api/v1/punchout/orderrequest:
    post:
      tags:
      - Punchout
      operationId: PunchOutV1_OrderRequestAsync
      parameters:
      - name: request
        in: query
        required: true
        schema:
          type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
            text/json:
              schema:
                type: object
            application/xml:
              schema:
                type: object
            text/xml:
              schema:
                type: object
            text/html:
              schema:
                type: object
components:
  securitySchemes:
    access_token:
      type: apiKey
      description: Token used to access storefront API.
      name: access_token
      in: query
