openapi: 3.2.0
info:
  version: admin-v1
  title: Admin API V1 Order Line Rfqs API
servers:
- url: https://dogfood.commerce.insitesandbox.com
security: []
tags:
- name: Order Line Rfqs
paths:
  /api/v1/admin/OrderLineRfqs:
    get:
      tags:
      - Order Line Rfqs
      summary: Returns the EntitySet OrderLineRfqs
      operationId: OrderLineRfqs_Get
      parameters:
      - name: $expand
        in: query
        description: Expands related entities inline.
        required: false
        schema:
          type: string
      - name: $filter
        in: query
        description: Filters the results, based on a Boolean condition.
        required: false
        schema:
          type: string
      - name: $select
        in: query
        description: Selects which properties to include in the response.
        required: false
        schema:
          type: string
      - name: $apply
        in: query
        description: Aggregates the results according to one or more transformations.
        required: false
        schema:
          type: string
      - name: $orderby
        in: query
        description: Sorts the results.
        required: false
        schema:
          type: string
      - name: $top
        in: query
        description: Returns only the first n results.
        required: false
        schema:
          type: integer
          format: int32
      - name: $skip
        in: query
        description: Skips the first n results.
        required: false
        schema:
          type: integer
          format: int32
      - name: $count
        in: query
        description: Includes a count of the matching results in the response.
        required: false
        schema:
          type: boolean
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                type: object
      deprecated: false
      security:
      - access_token: []
    post:
      tags:
      - Order Line Rfqs
      summary: Post a new entity to EntitySet OrderLineRfqs
      operationId: OrderLineRfqs_Post
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Insite.Data.Entities.OrderLineRfq'
        description: The entity to post
        required: true
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                type: object
      deprecated: false
      security:
      - access_token: []
  /api/v1/admin/OrderLineRfqs({id}):
    get:
      tags:
      - Order Line Rfqs
      summary: Returns the entity with the key from OrderLineRfqs
      operationId: OrderLineRfqs_GetById
      parameters:
      - name: id
        in: path
        description: 'key: id'
        required: true
        schema:
          type: string
          format: uuid
      - name: $expand
        in: query
        description: Expands related entities inline.
        required: false
        schema:
          type: string
      - name: $select
        in: query
        description: Selects which properties to include in the response.
        required: false
        schema:
          type: string
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                type: object
      deprecated: false
      security:
      - access_token: []
    put:
      tags:
      - Order Line Rfqs
      summary: Replace entity in EntitySet OrderLineRfqs
      operationId: OrderLineRfqs_PutById
      parameters:
      - name: id
        in: path
        description: 'key: id'
        required: true
        schema:
          type: string
          format: uuid
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Insite.Data.Entities.OrderLineRfq'
        description: The entity to put
        required: true
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                type: object
      deprecated: false
      security:
      - access_token: []
    delete:
      tags:
      - Order Line Rfqs
      summary: Delete entity in EntitySet OrderLineRfqs
      operationId: OrderLineRfqs_DeleteById
      parameters:
      - name: id
        in: path
        description: 'key: id'
        required: true
        schema:
          type: string
          format: uuid
      - name: If-Match
        in: header
        description: If-Match header
        required: false
        schema:
          type: string
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                type: object
      deprecated: false
      security:
      - access_token: []
    patch:
      tags:
      - Order Line Rfqs
      summary: Update entity in EntitySet OrderLineRfqs
      operationId: OrderLineRfqs_PatchById
      parameters:
      - name: id
        in: path
        description: 'key: id'
        required: true
        schema:
          type: string
          format: uuid
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Insite.Data.Entities.OrderLineRfq'
        description: The entity to patch
        required: true
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                type: object
      deprecated: false
      security:
      - access_token: []
  /api/v1/admin/OrderLineRfqs/Default.Default():
    get:
      tags:
      - Order Line Rfqs
      summary: Call operation  Default
      operationId: OrderLineRfqs_Default
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                type: object
      deprecated: false
      security:
      - access_token: []
  /api/v1/admin/orderlinerfqs/delete:
    delete:
      tags:
      - Order Line Rfqs
      operationId: OrderLineRfqs_DeleteRoute
      parameters:
      - name: ids
        in: query
        required: true
        explode: true
        schema:
          type: array
          items:
            type: string
            format: uuid
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                type: object
      deprecated: false
      security:
      - access_token: []
  /api/v1/admin/orderlinerfqs({key})/customproperties({custompropertyKey}):
    get:
      tags:
      - Order Line Rfqs
      operationId: OrderLineRfqs_GetCustomPropertyByKeyAndCustompropertykey
      parameters:
      - name: key
        in: path
        required: true
        schema:
          type: string
          format: uuid
      - name: custompropertyKey
        in: path
        required: true
        schema:
          type: string
          format: uuid
      - name: $expand
        in: query
        description: Expands related entities inline.
        required: false
        schema:
          type: string
      - name: $select
        in: query
        description: Selects which properties to include in the response.
        required: false
        schema:
          type: string
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                type: object
      deprecated: false
      security:
      - access_token: []
components:
  schemas:
    Insite.Data.Entities.OrderLineRfq:
      type: object
      properties:
        id:
          format: uuid
          type: string
          example: 00000000-0000-0000-0000-000000000000
        orderLineId:
          format: uuid
          type: string
          example: 00000000-0000-0000-0000-000000000000
        breakQty01:
          format: decimal
          type: number
        breakQty02:
          format: decimal
          type: number
        breakQty03:
          format: decimal
          type: number
        breakQty04:
          format: decimal
          type: number
        breakQty05:
          format: decimal
          type: number
        breakQty06:
          format: decimal
          type: number
        breakQty07:
          format: decimal
          type: number
        breakQty08:
          format: decimal
          type: number
        breakQty09:
          format: decimal
          type: number
        breakQty10:
          format: decimal
          type: number
        breakQty11:
          format: decimal
          type: number
        amount01:
          format: decimal
          type: number
        amount02:
          format: decimal
          type: number
        amount03:
          format: decimal
          type: number
        amount04:
          format: decimal
          type: number
        amount05:
          format: decimal
          type: number
        amount06:
          format: decimal
          type: number
        amount07:
          format: decimal
          type: number
        amount08:
          format: decimal
          type: number
        amount09:
          format: decimal
          type: number
        amount10:
          format: decimal
          type: number
        amount11:
          format: decimal
          type: number
        maxQty:
          format: decimal
          type: number
        createdOn:
          format: date-time
          type: string
        createdBy:
          type: string
        modifiedOn:
          format: date-time
          type: string
        modifiedBy:
          type: string
  securitySchemes:
    access_token:
      type: apiKey
      description: Token used to access storefront API.
      name: access_token
      in: query
