openapi: 3.2.0
info:
  version: admin-v1
  title: Admin API V1 Content Items API
servers:
- url: https://dogfood.commerce.insitesandbox.com
security: []
tags:
- name: Content Items
paths:
  /api/v1/admin/ContentItems:
    get:
      tags:
      - Content Items
      summary: Returns the EntitySet ContentItems
      operationId: ContentItems_Get
      parameters:
      - name: $expand
        in: query
        description: Expands related entities inline.
        required: false
        schema:
          type: string
      - name: $filter
        in: query
        description: Filters the results, based on a Boolean condition.
        required: false
        schema:
          type: string
      - name: $select
        in: query
        description: Selects which properties to include in the response.
        required: false
        schema:
          type: string
      - name: $apply
        in: query
        description: Aggregates the results according to one or more transformations.
        required: false
        schema:
          type: string
      - name: $orderby
        in: query
        description: Sorts the results.
        required: false
        schema:
          type: string
      - name: $top
        in: query
        description: Returns only the first n results.
        required: false
        schema:
          type: integer
          format: int32
      - name: $skip
        in: query
        description: Skips the first n results.
        required: false
        schema:
          type: integer
          format: int32
      - name: $count
        in: query
        description: Includes a count of the matching results in the response.
        required: false
        schema:
          type: boolean
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                type: object
      deprecated: false
      security:
      - access_token: []
    post:
      tags:
      - Content Items
      summary: Post a new entity to EntitySet ContentItems
      operationId: ContentItems_Post
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Insite.Data.Entities.ContentItem'
        description: The entity to post
        required: true
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                type: object
      deprecated: false
      security:
      - access_token: []
  /api/v1/admin/ContentItems({id}):
    get:
      tags:
      - Content Items
      summary: Returns the entity with the key from ContentItems
      operationId: ContentItems_GetById
      parameters:
      - name: id
        in: path
        description: 'key: id'
        required: true
        schema:
          type: string
          format: uuid
      - name: $expand
        in: query
        description: Expands related entities inline.
        required: false
        schema:
          type: string
      - name: $select
        in: query
        description: Selects which properties to include in the response.
        required: false
        schema:
          type: string
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                type: object
      deprecated: false
      security:
      - access_token: []
    put:
      tags:
      - Content Items
      summary: Replace entity in EntitySet ContentItems
      operationId: ContentItems_PutById
      parameters:
      - name: id
        in: path
        description: 'key: id'
        required: true
        schema:
          type: string
          format: uuid
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Insite.Data.Entities.ContentItem'
        description: The entity to put
        required: true
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                type: object
      deprecated: false
      security:
      - access_token: []
    delete:
      tags:
      - Content Items
      summary: Delete entity in EntitySet ContentItems
      operationId: ContentItems_DeleteById
      parameters:
      - name: id
        in: path
        description: 'key: id'
        required: true
        schema:
          type: string
          format: uuid
      - name: If-Match
        in: header
        description: If-Match header
        required: false
        schema:
          type: string
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                type: object
      deprecated: false
      security:
      - access_token: []
    patch:
      tags:
      - Content Items
      summary: Update entity in EntitySet ContentItems
      operationId: ContentItems_PatchById
      parameters:
      - name: id
        in: path
        description: 'key: id'
        required: true
        schema:
          type: string
          format: uuid
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Insite.Data.Entities.ContentItem'
        description: The entity to patch
        required: true
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                type: object
      deprecated: false
      security:
      - access_token: []
  /api/v1/admin/ContentItems/Default.Default():
    get:
      tags:
      - Content Items
      summary: Call operation  Default
      operationId: ContentItems_Default
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                type: object
      deprecated: false
      security:
      - access_token: []
  /api/v1/admin/contentitems/delete:
    delete:
      tags:
      - Content Items
      operationId: ContentItems_DeleteRoute
      parameters:
      - name: ids
        in: query
        required: true
        explode: true
        schema:
          type: array
          items:
            type: string
            format: uuid
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                type: object
      deprecated: false
      security:
      - access_token: []
  /api/v1/admin/contentitems({key})/customproperties({custompropertyKey}):
    get:
      tags:
      - Content Items
      operationId: ContentItems_GetCustomPropertyByKeyAndCustompropertykey
      parameters:
      - name: key
        in: path
        required: true
        schema:
          type: string
          format: uuid
      - name: custompropertyKey
        in: path
        required: true
        schema:
          type: string
          format: uuid
      - name: $expand
        in: query
        description: Expands related entities inline.
        required: false
        schema:
          type: string
      - name: $select
        in: query
        description: Selects which properties to include in the response.
        required: false
        schema:
          type: string
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                type: object
      deprecated: false
      security:
      - access_token: []
components:
  schemas:
    Insite.Data.Entities.ContentItem:
      required:
      - class
      - path
      - name
      - variantName
      - zone
      - templateView
      type: object
      properties:
        id:
          format: uuid
          type: string
          example: 00000000-0000-0000-0000-000000000000
        class:
          maxLength: 50
          minLength: 0
          type: string
        contentKey:
          format: int32
          type: integer
        parentKey:
          format: int32
          type: integer
        pageContentKey:
          format: int32
          type: integer
        variantKey:
          format: int32
          type: integer
        path:
          maxLength: 500
          minLength: 0
          type: string
        isPage:
          type: boolean
        sortOrder:
          format: int32
          type: integer
        publishOn:
          format: date-time
          type: string
        websiteId:
          format: uuid
          type: string
          example: 00000000-0000-0000-0000-000000000000
        approvedOn:
          format: date-time
          type: string
        submittedForApprovalOn:
          format: date-time
          type: string
        createdById:
          format: uuid
          type: string
          example: 00000000-0000-0000-0000-000000000000
        approvedById:
          format: uuid
          type: string
          example: 00000000-0000-0000-0000-000000000000
        isRetracted:
          type: boolean
        name:
          maxLength: 50
          minLength: 0
          type: string
        variantName:
          maxLength: 50
          minLength: 0
          type: string
        zone:
          maxLength: 100
          minLength: 0
          type: string
        linkedToContentKey:
          format: int32
          type: integer
        syncLinkedToChildren:
          type: boolean
        isTemplate:
          type: boolean
        templateContentKey:
          format: int32
          type: integer
        useDefaultTemplate:
          type: boolean
        templateView:
          maxLength: 100
          minLength: 0
          type: string
        isDeleted:
          type: boolean
        isDefaultVariant:
          type: boolean
        ruleManagerId:
          format: uuid
          type: string
          example: 00000000-0000-0000-0000-000000000000
        experimentId:
          format: uuid
          type: string
          example: 00000000-0000-0000-0000-000000000000
        isRollback:
          type: boolean
        isMobileAppPage:
          type: boolean
        createdOn:
          format: date-time
          type: string
        createdBy:
          type: string
        modifiedOn:
          format: date-time
          type: string
        modifiedBy:
          type: string
  securitySchemes:
    access_token:
      type: apiKey
      description: Token used to access storefront API.
      name: access_token
      in: query
