openapi: 3.2.0
info:
  version: admin-v1
  title: Admin API V1 System Files API
servers:
- url: https://dogfood.commerce.insitesandbox.com
security: []
tags:
- name: System Files
paths:
  /api/v1/admin/systemfiles:
    get:
      tags:
      - System Files
      operationId: SystemFilesV1_GetAsync
      parameters:
      - name: path
        in: query
        required: true
        schema:
          type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
            text/json:
              schema:
                type: object
            application/xml:
              schema:
                type: object
            text/xml:
              schema:
                type: object
            text/html:
              schema:
                type: object
      security:
      - access_token: []
  /api/v1/admin/systemfiles/content:
    post:
      tags:
      - System Files
      operationId: SystemFilesV1_ContentAsync
      parameters:
      - name: path
        in: query
        required: true
        schema:
          type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
            text/json:
              schema:
                type: object
            application/xml:
              schema:
                type: object
            text/xml:
              schema:
                type: object
            text/html:
              schema:
                type: object
      security:
      - access_token: []
components:
  securitySchemes:
    access_token:
      type: apiKey
      description: Token used to access storefront API.
      name: access_token
      in: query
